
package org.milleni.dunning.ws.client.milldesk;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "milldeskSoap", targetNamespace = "http://bizmonws.milleni.com.tr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MilldeskSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Version", action = "http://bizmonws.milleni.com.tr/Version")
    @WebResult(name = "VersionResult", targetNamespace = "http://bizmonws.milleni.com.tr/")
    @RequestWrapper(localName = "Version", targetNamespace = "http://bizmonws.milleni.com.tr/", className = "org.milleni.dunning.ws.client.milldesk.Version")
    @ResponseWrapper(localName = "VersionResponse", targetNamespace = "http://bizmonws.milleni.com.tr/", className = "org.milleni.dunning.ws.client.milldesk.VersionResponse")
    public String version();

    /**
     * 
     * @param sMessage
     * @param sAltDurum
     * @param sStatus
     * @param sTalepKonusu
     * @param customerID
     * @param sNeden
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Add_Task_Quick", action = "http://bizmonws.milleni.com.tr/Add_Task_Quick")
    @WebResult(name = "Add_Task_QuickResult", targetNamespace = "http://bizmonws.milleni.com.tr/")
    @RequestWrapper(localName = "Add_Task_Quick", targetNamespace = "http://bizmonws.milleni.com.tr/", className = "org.milleni.dunning.ws.client.milldesk.AddTaskQuick")
    @ResponseWrapper(localName = "Add_Task_QuickResponse", targetNamespace = "http://bizmonws.milleni.com.tr/", className = "org.milleni.dunning.ws.client.milldesk.AddTaskQuickResponse")
    public String addTaskQuick(
        @WebParam(name = "CustomerID", targetNamespace = "http://bizmonws.milleni.com.tr/")
        int customerID,
        @WebParam(name = "sNeden", targetNamespace = "http://bizmonws.milleni.com.tr/")
        String sNeden,
        @WebParam(name = "sTalepKonusu", targetNamespace = "http://bizmonws.milleni.com.tr/")
        String sTalepKonusu,
        @WebParam(name = "sAltDurum", targetNamespace = "http://bizmonws.milleni.com.tr/")
        String sAltDurum,
        @WebParam(name = "sStatus", targetNamespace = "http://bizmonws.milleni.com.tr/")
        String sStatus,
        @WebParam(name = "sMessage", targetNamespace = "http://bizmonws.milleni.com.tr/")
        String sMessage);

    /**
     * 
     * @param sMobile
     * @param sStatus
     * @param sCustomerType
     * @param sTalepKonusu
     * @param sNeden
     * @param sMessage
     * @param sEmail
     * @param sAltDurum
     * @param sDealaer
     * @param sCustomerName
     * @param sRequestKind
     * @param customerID
     * @param contractID
     * @param sDealerCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Add_Task_Ext", action = "http://bizmonws.milleni.com.tr/Add_Task_Ext")
    @WebResult(name = "Add_Task_ExtResult", targetNamespace = "http://bizmonws.milleni.com.tr/")
    @RequestWrapper(localName = "Add_Task_Ext", targetNamespace = "http://bizmonws.milleni.com.tr/", className = "org.milleni.dunning.ws.client.milldesk.AddTaskExt")
    @ResponseWrapper(localName = "Add_Task_ExtResponse", targetNamespace = "http://bizmonws.milleni.com.tr/", className = "org.milleni.dunning.ws.client.milldesk.AddTaskExtResponse")
    public String addTaskExt(
        @WebParam(name = "CustomerID", targetNamespace = "http://bizmonws.milleni.com.tr/")
        int customerID,
        @WebParam(name = "ContractID", targetNamespace = "http://bizmonws.milleni.com.tr/")
        int contractID,
        @WebParam(name = "sCustomerName", targetNamespace = "http://bizmonws.milleni.com.tr/")
        String sCustomerName,
        @WebParam(name = "sMobile", targetNamespace = "http://bizmonws.milleni.com.tr/")
        String sMobile,
        @WebParam(name = "sEmail", targetNamespace = "http://bizmonws.milleni.com.tr/")
        String sEmail,
        @WebParam(name = "sDealaer", targetNamespace = "http://bizmonws.milleni.com.tr/")
        String sDealaer,
        @WebParam(name = "sDealerCode", targetNamespace = "http://bizmonws.milleni.com.tr/")
        String sDealerCode,
        @WebParam(name = "sCustomerType", targetNamespace = "http://bizmonws.milleni.com.tr/")
        String sCustomerType,
        @WebParam(name = "sRequestKind", targetNamespace = "http://bizmonws.milleni.com.tr/")
        String sRequestKind,
        @WebParam(name = "sNeden", targetNamespace = "http://bizmonws.milleni.com.tr/")
        String sNeden,
        @WebParam(name = "sTalepKonusu", targetNamespace = "http://bizmonws.milleni.com.tr/")
        String sTalepKonusu,
        @WebParam(name = "sAltDurum", targetNamespace = "http://bizmonws.milleni.com.tr/")
        String sAltDurum,
        @WebParam(name = "sStatus", targetNamespace = "http://bizmonws.milleni.com.tr/")
        String sStatus,
        @WebParam(name = "sMessage", targetNamespace = "http://bizmonws.milleni.com.tr/")
        String sMessage);

    /**
     * 
     * @param customerID
     * @return
     *     returns int
     */
    @WebMethod(action = "http://bizmonws.milleni.com.tr/retrieveOpenTicklerCount")
    @WebResult(name = "retrieveOpenTicklerCountResult", targetNamespace = "http://bizmonws.milleni.com.tr/")
    @RequestWrapper(localName = "retrieveOpenTicklerCount", targetNamespace = "http://bizmonws.milleni.com.tr/", className = "org.milleni.dunning.ws.client.milldesk.RetrieveOpenTicklerCount")
    @ResponseWrapper(localName = "retrieveOpenTicklerCountResponse", targetNamespace = "http://bizmonws.milleni.com.tr/", className = "org.milleni.dunning.ws.client.milldesk.RetrieveOpenTicklerCountResponse")
    public int retrieveOpenTicklerCount(
        @WebParam(name = "CustomerID", targetNamespace = "http://bizmonws.milleni.com.tr/")
        int customerID);

}
