
package org.milleni.dunning.ws.client.milldesk;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "milldesk", targetNamespace = "http://bizmonws.milleni.com.tr/", wsdlLocation = "http://localhost:45271/milldesk.asmx?WSDL")
public class Milldesk
    extends Service
{

    private final static URL MILLDESK_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.milleni.dunning.ws.client.milldesk.Milldesk.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.milleni.dunning.ws.client.milldesk.Milldesk.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:45271/milldesk.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:45271/milldesk.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MILLDESK_WSDL_LOCATION = url;
    }

    public Milldesk(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Milldesk() {
        super(MILLDESK_WSDL_LOCATION, new QName("http://bizmonws.milleni.com.tr/", "milldesk"));
    }

    /**
     * 
     * @return
     *     returns MilldeskSoap
     */
    @WebEndpoint(name = "milldeskSoap")
    public MilldeskSoap getMilldeskSoap() {
        return super.getPort(new QName("http://bizmonws.milleni.com.tr/", "milldeskSoap"), MilldeskSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MilldeskSoap
     */
    @WebEndpoint(name = "milldeskSoap")
    public MilldeskSoap getMilldeskSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://bizmonws.milleni.com.tr/", "milldeskSoap"), MilldeskSoap.class, features);
    }

}
