
package org.milleni.dunning.ws.client.crm;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CustomerInfoServiceV1", targetNamespace = "/CustomerInfo/Service/v1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerInfoServiceV1 {


    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.QueryCustomerResponseModel
     * @throws CustomerInfoServiceV1QueryCustomerBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1QueryCustomerSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "QueryCustomer", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/QueryCustomer")
    @WebResult(name = "QueryCustomerResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "QueryCustomer", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.QueryCustomer")
    @ResponseWrapper(localName = "QueryCustomerResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.QueryCustomerResponse")
    public QueryCustomerResponseModel queryCustomer(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        QueryCustomerRequestModel request)
        throws CustomerInfoServiceV1QueryCustomerBusinessFaultFaultFaultMessage, CustomerInfoServiceV1QueryCustomerSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.GetCustomerResponseModel
     * @throws CustomerInfoServiceV1GetCustomerBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1GetCustomerSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCustomer", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/GetCustomer")
    @WebResult(name = "GetCustomerResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "GetCustomer", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.GetCustomer")
    @ResponseWrapper(localName = "GetCustomerResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.GetCustomerResponse")
    public GetCustomerResponseModel getCustomer(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        GetCustomerRequestModel request)
        throws CustomerInfoServiceV1GetCustomerBusinessFaultFaultFaultMessage, CustomerInfoServiceV1GetCustomerSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.GetCustomerResponseModel
     * @throws CustomerInfoServiceV1GetCustomerByCustomerIdBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1GetCustomerByCustomerIdSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCustomerByCustomerId", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/GetCustomerByCustomerId")
    @WebResult(name = "GetCustomerByCustomerIdResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "GetCustomerByCustomerId", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.GetCustomerByCustomerId")
    @ResponseWrapper(localName = "GetCustomerByCustomerIdResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.GetCustomerByCustomerIdResponse")
    public GetCustomerResponseModel getCustomerByCustomerId(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        GetCustomerRequestModel request)
        throws CustomerInfoServiceV1GetCustomerByCustomerIdBusinessFaultFaultFaultMessage, CustomerInfoServiceV1GetCustomerByCustomerIdSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.UserResponseModel
     * @throws CustomerInfoServiceV1AddUserSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1AddUserBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddUser", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/AddUser")
    @WebResult(name = "AddUserResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "AddUser", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AddUser")
    @ResponseWrapper(localName = "AddUserResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AddUserResponse")
    public UserResponseModel addUser(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        UserRequestModel request)
        throws CustomerInfoServiceV1AddUserBusinessFaultFaultFaultMessage, CustomerInfoServiceV1AddUserSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.UserResponseModel
     * @throws CustomerInfoServiceV1DeleteUserSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1DeleteUserBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "DeleteUser", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/DeleteUser")
    @WebResult(name = "DeleteUserResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "DeleteUser", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.DeleteUser")
    @ResponseWrapper(localName = "DeleteUserResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.DeleteUserResponse")
    public UserResponseModel deleteUser(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        UserRequestModel request)
        throws CustomerInfoServiceV1DeleteUserBusinessFaultFaultFaultMessage, CustomerInfoServiceV1DeleteUserSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.QueryStockItemResponseModel
     * @throws CustomerInfoServiceV1QueryStockItemBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1QueryStockItemSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "QueryStockItem", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/QueryStockItem")
    @WebResult(name = "QueryStockItemResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "QueryStockItem", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.QueryStockItem")
    @ResponseWrapper(localName = "QueryStockItemResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.QueryStockItemResponse")
    public QueryStockItemResponseModel queryStockItem(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        QueryStockItemRequestModel request)
        throws CustomerInfoServiceV1QueryStockItemBusinessFaultFaultFaultMessage, CustomerInfoServiceV1QueryStockItemSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ListStockItemResponseModel
     * @throws CustomerInfoServiceV1ListStockItemSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ListStockItemBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ListStockItem", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ListStockItem")
    @WebResult(name = "ListStockItemResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ListStockItem", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ListStockItem")
    @ResponseWrapper(localName = "ListStockItemResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ListStockItemResponse")
    public ListStockItemResponseModel listStockItem(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ListStockItemRequestModel request)
        throws CustomerInfoServiceV1ListStockItemBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ListStockItemSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.QueryStockItemResponseModel
     * @throws CustomerInfoServiceV1QueryStockItemByStateBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1QueryStockItemByStateSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "QueryStockItemByState", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/QueryStockItemByState")
    @WebResult(name = "QueryStockItemByStateResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "QueryStockItemByState", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.QueryStockItemByState")
    @ResponseWrapper(localName = "QueryStockItemByStateResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.QueryStockItemByStateResponse")
    public QueryStockItemResponseModel queryStockItemByState(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        QueryStockItemByStateRequestModel request)
        throws CustomerInfoServiceV1QueryStockItemByStateBusinessFaultFaultFaultMessage, CustomerInfoServiceV1QueryStockItemByStateSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.QueryStockItemOuidResponseModel
     * @throws CustomerInfoServiceV1QueryStockItemOuidBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1QueryStockItemOuidSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "QueryStockItemOuid", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/QueryStockItemOuid")
    @WebResult(name = "QueryStockItemOuidResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "QueryStockItemOuid", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.QueryStockItemOuid")
    @ResponseWrapper(localName = "QueryStockItemOuidResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.QueryStockItemOuidResponse")
    public QueryStockItemOuidResponseModel queryStockItemOuid(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        QueryStockItemOuidRequestModel request)
        throws CustomerInfoServiceV1QueryStockItemOuidBusinessFaultFaultFaultMessage, CustomerInfoServiceV1QueryStockItemOuidSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.StockItemsResponseModel
     * @throws CustomerInfoServiceV1GetCustomerStockItemsSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1GetCustomerStockItemsBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCustomerStockItems", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/GetCustomerStockItems")
    @WebResult(name = "GetCustomerStockItemsResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "GetCustomerStockItems", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.GetCustomerStockItems")
    @ResponseWrapper(localName = "GetCustomerStockItemsResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.GetCustomerStockItemsResponse")
    public StockItemsResponseModel getCustomerStockItems(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        GetCustomerStockItemsRequestModel request)
        throws CustomerInfoServiceV1GetCustomerStockItemsBusinessFaultFaultFaultMessage, CustomerInfoServiceV1GetCustomerStockItemsSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ChangeStockItemStatusResponseModel
     * @throws CustomerInfoServiceV1FaultyStockItemsBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1FaultyStockItemsSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "FaultyStockItems", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/FaultyStockItems")
    @WebResult(name = "FaultyStockItemsResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "FaultyStockItems", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.FaultyStockItems")
    @ResponseWrapper(localName = "FaultyStockItemsResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.FaultyStockItemsResponse")
    public ChangeStockItemStatusResponseModel faultyStockItems(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        FaultyStockItemsRequestModel request)
        throws CustomerInfoServiceV1FaultyStockItemsBusinessFaultFaultFaultMessage, CustomerInfoServiceV1FaultyStockItemsSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ChangeStockItemStatusResponseModel
     * @throws CustomerInfoServiceV1ReserveStockItemBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ReserveStockItemSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ReserveStockItem", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ReserveStockItem")
    @WebResult(name = "ReserveStockItemResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ReserveStockItem", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ReserveStockItem")
    @ResponseWrapper(localName = "ReserveStockItemResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ReserveStockItemResponse")
    public ChangeStockItemStatusResponseModel reserveStockItem(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ReserveStockItemRequestModel request)
        throws CustomerInfoServiceV1ReserveStockItemBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ReserveStockItemSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ChangeStockItemStatusResponseModel
     * @throws CustomerInfoServiceV1AssignStockItemSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1AssignStockItemBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AssignStockItem", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/AssignStockItem")
    @WebResult(name = "AssignStockItemResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "AssignStockItem", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AssignStockItem")
    @ResponseWrapper(localName = "AssignStockItemResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AssignStockItemResponse")
    public ChangeStockItemStatusResponseModel assignStockItem(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        AssignStockItemRequestModel request)
        throws CustomerInfoServiceV1AssignStockItemBusinessFaultFaultFaultMessage, CustomerInfoServiceV1AssignStockItemSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ChangeStockItemStatusResponseModel
     * @throws CustomerInfoServiceV1AssignStockItemsBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1AssignStockItemsSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AssignStockItems", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/AssignStockItems")
    @WebResult(name = "AssignStockItemsResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "AssignStockItems", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AssignStockItems")
    @ResponseWrapper(localName = "AssignStockItemsResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AssignStockItemsResponse")
    public ChangeStockItemStatusResponseModel assignStockItems(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        AssignStockItemsRequestModel request)
        throws CustomerInfoServiceV1AssignStockItemsBusinessFaultFaultFaultMessage, CustomerInfoServiceV1AssignStockItemsSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ChangeStockItemStatusResponseModel
     * @throws CustomerInfoServiceV1ReleaseStockItemSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ReleaseStockItemBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ReleaseStockItem", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ReleaseStockItem")
    @WebResult(name = "ReleaseStockItemResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ReleaseStockItem", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ReleaseStockItem")
    @ResponseWrapper(localName = "ReleaseStockItemResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ReleaseStockItemResponse")
    public ChangeStockItemStatusResponseModel releaseStockItem(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ReleaseStockItemRequestModel request)
        throws CustomerInfoServiceV1ReleaseStockItemBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ReleaseStockItemSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ChangeStockItemStatusResponseModel
     * @throws CustomerInfoServiceV1SetStockItemStatusControlSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1SetStockItemStatusControlBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SetStockItemStatusControl", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/SetStockItemStatusControl")
    @WebResult(name = "SetStockItemStatusControlResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "SetStockItemStatusControl", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.SetStockItemStatusControl")
    @ResponseWrapper(localName = "SetStockItemStatusControlResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.SetStockItemStatusControlResponse")
    public ChangeStockItemStatusResponseModel setStockItemStatusControl(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ChangeStockItemStatusRequestModel request)
        throws CustomerInfoServiceV1SetStockItemStatusControlBusinessFaultFaultFaultMessage, CustomerInfoServiceV1SetStockItemStatusControlSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ChangeStockItemStatusResponseModel
     * @throws CustomerInfoServiceV1SetStockItemStatusBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1SetStockItemStatusSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SetStockItemStatus", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/SetStockItemStatus")
    @WebResult(name = "SetStockItemStatusResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "SetStockItemStatus", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.SetStockItemStatus")
    @ResponseWrapper(localName = "SetStockItemStatusResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.SetStockItemStatusResponse")
    public ChangeStockItemStatusResponseModel setStockItemStatus(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ChangeStockItemStatusRequestModel request)
        throws CustomerInfoServiceV1SetStockItemStatusBusinessFaultFaultFaultMessage, CustomerInfoServiceV1SetStockItemStatusSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ChangeStockItemStatusResponseModel
     * @throws CustomerInfoServiceV1SetStockItemStatusOperationalTracingSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1SetStockItemStatusOperationalTracingBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SetStockItemStatusOperationalTracing", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/SetStockItemStatusOperationalTracing")
    @WebResult(name = "SetStockItemStatusOperationalTracingResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "SetStockItemStatusOperationalTracing", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.SetStockItemStatusOperationalTracing")
    @ResponseWrapper(localName = "SetStockItemStatusOperationalTracingResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.SetStockItemStatusOperationalTracingResponse")
    public ChangeStockItemStatusResponseModel setStockItemStatusOperationalTracing(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ChangeStockItemStatusRequestModel request)
        throws CustomerInfoServiceV1SetStockItemStatusOperationalTracingBusinessFaultFaultFaultMessage, CustomerInfoServiceV1SetStockItemStatusOperationalTracingSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ChangeStockItemStatusResponseModel
     * @throws CustomerInfoServiceV1SetStockItemStatusAssignedSupportBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1SetStockItemStatusAssignedSupportSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SetStockItemStatusAssignedSupport", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/SetStockItemStatusAssignedSupport")
    @WebResult(name = "SetStockItemStatusAssignedSupportResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "SetStockItemStatusAssignedSupport", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.SetStockItemStatusAssignedSupport")
    @ResponseWrapper(localName = "SetStockItemStatusAssignedSupportResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.SetStockItemStatusAssignedSupportResponse")
    public ChangeStockItemStatusResponseModel setStockItemStatusAssignedSupport(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ChangeStockItemStatusRequestModel request)
        throws CustomerInfoServiceV1SetStockItemStatusAssignedSupportBusinessFaultFaultFaultMessage, CustomerInfoServiceV1SetStockItemStatusAssignedSupportSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ChangeStockItemStatusResponseModel
     * @throws CustomerInfoServiceV1SetStockItemStatusBilledSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1SetStockItemStatusBilledBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SetStockItemStatusBilled", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/SetStockItemStatusBilled")
    @WebResult(name = "SetStockItemStatusBilledResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "SetStockItemStatusBilled", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.SetStockItemStatusBilled")
    @ResponseWrapper(localName = "SetStockItemStatusBilledResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.SetStockItemStatusBilledResponse")
    public ChangeStockItemStatusResponseModel setStockItemStatusBilled(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ChangeStockItemStatusRequestModel request)
        throws CustomerInfoServiceV1SetStockItemStatusBilledBusinessFaultFaultFaultMessage, CustomerInfoServiceV1SetStockItemStatusBilledSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ChangeStockItemStatusResponseModel
     * @throws CustomerInfoServiceV1SetStockItemStatusAssignedBilledSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1SetStockItemStatusAssignedBilledBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SetStockItemStatusAssignedBilled", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/SetStockItemStatusAssignedBilled")
    @WebResult(name = "SetStockItemStatusAssignedBilledResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "SetStockItemStatusAssignedBilled", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.SetStockItemStatusAssignedBilled")
    @ResponseWrapper(localName = "SetStockItemStatusAssignedBilledResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.SetStockItemStatusAssignedBilledResponse")
    public ChangeStockItemStatusResponseModel setStockItemStatusAssignedBilled(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ChangeStockItemStatusRequestModel request)
        throws CustomerInfoServiceV1SetStockItemStatusAssignedBilledBusinessFaultFaultFaultMessage, CustomerInfoServiceV1SetStockItemStatusAssignedBilledSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.CRMProvisionResponseModel
     * @throws CustomerInfoServiceV1ProvisionOrderItemToCRMSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ProvisionOrderItemToCRMBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ProvisionOrderItemToCRM", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ProvisionOrderItemToCRM")
    @WebResult(name = "ProvisionOrderItemToCRMResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ProvisionOrderItemToCRM", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ProvisionOrderItemToCRM")
    @ResponseWrapper(localName = "ProvisionOrderItemToCRMResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ProvisionOrderItemToCRMResponse")
    public CRMProvisionResponseModel provisionOrderItemToCRM(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        CRMProvisionRequestModel request)
        throws CustomerInfoServiceV1ProvisionOrderItemToCRMBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ProvisionOrderItemToCRMSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @throws CustomerInfoServiceV1CrmDocumentUpdateAfterSetupSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1CrmDocumentUpdateAfterSetupBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "CrmDocumentUpdateAfterSetup", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/CrmDocumentUpdateAfterSetup")
    @RequestWrapper(localName = "CrmDocumentUpdateAfterSetup", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.CrmDocumentUpdateAfterSetup")
    @ResponseWrapper(localName = "CrmDocumentUpdateAfterSetupResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.CrmDocumentUpdateAfterSetupResponse")
    public void crmDocumentUpdateAfterSetup(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        CRMProvisionRequestModel request)
        throws CustomerInfoServiceV1CrmDocumentUpdateAfterSetupBusinessFaultFaultFaultMessage, CustomerInfoServiceV1CrmDocumentUpdateAfterSetupSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.GetNumbersFromPoolResponseModel
     * @throws CustomerInfoServiceV1GetNumbersFromPoolSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1GetNumbersFromPoolBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetNumbersFromPool", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/GetNumbersFromPool")
    @WebResult(name = "GetNumbersFromPoolResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "GetNumbersFromPool", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.GetNumbersFromPool")
    @ResponseWrapper(localName = "GetNumbersFromPoolResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.GetNumbersFromPoolResponse")
    public GetNumbersFromPoolResponseModel getNumbersFromPool(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        GetNumbersFromPoolRequestModel request)
        throws CustomerInfoServiceV1GetNumbersFromPoolBusinessFaultFaultFaultMessage, CustomerInfoServiceV1GetNumbersFromPoolSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.QueryNumberPoolItemResponseModel
     * @throws CustomerInfoServiceV1QueryNumberPoolItemBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1QueryNumberPoolItemSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "QueryNumberPoolItem", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/QueryNumberPoolItem")
    @WebResult(name = "QueryNumberPoolItemResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "QueryNumberPoolItem", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.QueryNumberPoolItem")
    @ResponseWrapper(localName = "QueryNumberPoolItemResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.QueryNumberPoolItemResponse")
    public QueryNumberPoolItemResponseModel queryNumberPoolItem(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        QueryNumberPoolItemRequestModel request)
        throws CustomerInfoServiceV1QueryNumberPoolItemBusinessFaultFaultFaultMessage, CustomerInfoServiceV1QueryNumberPoolItemSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ChangeNumberPoolItemStatusResponseModel
     * @throws CustomerInfoServiceV1ReserveNumberPoolItemBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ReserveNumberPoolItemSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ReserveNumberPoolItem", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ReserveNumberPoolItem")
    @WebResult(name = "ReserveNumberPoolItemResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ReserveNumberPoolItem", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ReserveNumberPoolItem")
    @ResponseWrapper(localName = "ReserveNumberPoolItemResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ReserveNumberPoolItemResponse")
    public ChangeNumberPoolItemStatusResponseModel reserveNumberPoolItem(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ReserveNumberPoolItemRequestModel request)
        throws CustomerInfoServiceV1ReserveNumberPoolItemBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ReserveNumberPoolItemSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ChangeNumberPoolItemStatusResponseModel
     * @throws CustomerInfoServiceV1AssignNumberPoolItemBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1AssignNumberPoolItemSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AssignNumberPoolItem", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/AssignNumberPoolItem")
    @WebResult(name = "AssignNumberPoolItemResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "AssignNumberPoolItem", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AssignNumberPoolItem")
    @ResponseWrapper(localName = "AssignNumberPoolItemResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AssignNumberPoolItemResponse")
    public ChangeNumberPoolItemStatusResponseModel assignNumberPoolItem(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        AssignNumberPoolItemRequestModel request)
        throws CustomerInfoServiceV1AssignNumberPoolItemBusinessFaultFaultFaultMessage, CustomerInfoServiceV1AssignNumberPoolItemSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ChangeNumberPoolItemStatusResponseModel
     * @throws CustomerInfoServiceV1ReleaseNumberPoolItemSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ReleaseNumberPoolItemBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ReleaseNumberPoolItem", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ReleaseNumberPoolItem")
    @WebResult(name = "ReleaseNumberPoolItemResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ReleaseNumberPoolItem", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ReleaseNumberPoolItem")
    @ResponseWrapper(localName = "ReleaseNumberPoolItemResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ReleaseNumberPoolItemResponse")
    public ChangeNumberPoolItemStatusResponseModel releaseNumberPoolItem(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ReleaseNumberPoolItemRequestModel request)
        throws CustomerInfoServiceV1ReleaseNumberPoolItemBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ReleaseNumberPoolItemSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ChangeNumberPoolItemStatusResponseModel
     * @throws CustomerInfoServiceV1BlockNumberPoolItemSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1BlockNumberPoolItemBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BlockNumberPoolItem", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/BlockNumberPoolItem")
    @WebResult(name = "BlockNumberPoolItemResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "BlockNumberPoolItem", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.BlockNumberPoolItem")
    @ResponseWrapper(localName = "BlockNumberPoolItemResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.BlockNumberPoolItemResponse")
    public ChangeNumberPoolItemStatusResponseModel blockNumberPoolItem(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        BlockNumberPoolItemRequestModel request)
        throws CustomerInfoServiceV1BlockNumberPoolItemBusinessFaultFaultFaultMessage, CustomerInfoServiceV1BlockNumberPoolItemSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ChangeNumberPoolItemStatusResponseModel
     * @throws CustomerInfoServiceV1UnavailableNumberPoolItemSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1UnavailableNumberPoolItemBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UnavailableNumberPoolItem", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/UnavailableNumberPoolItem")
    @WebResult(name = "UnavailableNumberPoolItemResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "UnavailableNumberPoolItem", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.UnavailableNumberPoolItem")
    @ResponseWrapper(localName = "UnavailableNumberPoolItemResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.UnavailableNumberPoolItemResponse")
    public ChangeNumberPoolItemStatusResponseModel unavailableNumberPoolItem(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        UnavailableNumberPoolItemRequestModel request)
        throws CustomerInfoServiceV1UnavailableNumberPoolItemBusinessFaultFaultFaultMessage, CustomerInfoServiceV1UnavailableNumberPoolItemSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ValidateContractDeactivationResponseModel
     * @throws CustomerInfoServiceV1ValidateContractDeactivationBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ValidateContractDeactivationSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ValidateContractDeactivation", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ValidateContractDeactivation")
    @WebResult(name = "ValidateContractDeactivationResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ValidateContractDeactivation", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ValidateContractDeactivation")
    @ResponseWrapper(localName = "ValidateContractDeactivationResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ValidateContractDeactivationResponse")
    public ValidateContractDeactivationResponseModel validateContractDeactivation(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ValidateContractDeactivationRequestModel request)
        throws CustomerInfoServiceV1ValidateContractDeactivationBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ValidateContractDeactivationSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.SuspendCustomerContractResponseModel
     * @throws CustomerInfoServiceV1SuspendCustomerContractBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1SuspendCustomerContractSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SuspendCustomerContract", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/SuspendCustomerContract")
    @WebResult(name = "SuspendCustomerContractResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "SuspendCustomerContract", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.SuspendCustomerContract")
    @ResponseWrapper(localName = "SuspendCustomerContractResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.SuspendCustomerContractResponse")
    public SuspendCustomerContractResponseModel suspendCustomerContract(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        SuspendCustomerContractRequestModel request)
        throws CustomerInfoServiceV1SuspendCustomerContractBusinessFaultFaultFaultMessage, CustomerInfoServiceV1SuspendCustomerContractSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ValidateContractActivationResponseModel
     * @throws CustomerInfoServiceV1ValidateContractActivationSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ValidateContractActivationBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ValidateContractActivation", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ValidateContractActivation")
    @WebResult(name = "ValidateContractActivationResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ValidateContractActivation", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ValidateContractActivation")
    @ResponseWrapper(localName = "ValidateContractActivationResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ValidateContractActivationResponse")
    public ValidateContractActivationResponseModel validateContractActivation(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ValidateContractActivationRequestModel request)
        throws CustomerInfoServiceV1ValidateContractActivationBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ValidateContractActivationSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ActivateCustomerContractResponseModel
     * @throws CustomerInfoServiceV1ActivateCustomerContractSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ActivateCustomerContractBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ActivateCustomerContract", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ActivateCustomerContract")
    @WebResult(name = "ActivateCustomerContractResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ActivateCustomerContract", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ActivateCustomerContract")
    @ResponseWrapper(localName = "ActivateCustomerContractResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ActivateCustomerContractResponse")
    public ActivateCustomerContractResponseModel activateCustomerContract(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ActivateCustomerContractRequestModel request)
        throws CustomerInfoServiceV1ActivateCustomerContractBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ActivateCustomerContractSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.AddNumbersToContractResponseModel
     * @throws CustomerInfoServiceV1AddNumbersToContractBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1AddNumbersToContractSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddNumbersToContract", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/AddNumbersToContract")
    @WebResult(name = "AddNumbersToContractResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "AddNumbersToContract", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AddNumbersToContract")
    @ResponseWrapper(localName = "AddNumbersToContractResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AddNumbersToContractResponse")
    public AddNumbersToContractResponseModel addNumbersToContract(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        AddNumbersToContractRequestModel request)
        throws CustomerInfoServiceV1AddNumbersToContractBusinessFaultFaultFaultMessage, CustomerInfoServiceV1AddNumbersToContractSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ActivateAccountResponseModel
     * @throws CustomerInfoServiceV1ActivateAccountBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ActivateAccountSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ActivateAccount", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ActivateAccount")
    @WebResult(name = "ActivateAccountResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ActivateAccount", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ActivateAccount")
    @ResponseWrapper(localName = "ActivateAccountResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ActivateAccountResponse")
    public ActivateAccountResponseModel activateAccount(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ActivateAccountRequestModel request)
        throws CustomerInfoServiceV1ActivateAccountBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ActivateAccountSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     */
    @WebMethod(operationName = "ActivateAccountOneWay", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ActivateAccountOneWay")
    @Oneway
    @RequestWrapper(localName = "ActivateAccountOneWay", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ActivateAccountOneWay")
    public void activateAccountOneWay(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ActivateAccountRequestModel request);

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.SuspendAccountResponseModel
     * @throws CustomerInfoServiceV1SuspendAccountSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1SuspendAccountBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SuspendAccount", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/SuspendAccount")
    @WebResult(name = "SuspendAccountResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "SuspendAccount", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.SuspendAccount")
    @ResponseWrapper(localName = "SuspendAccountResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.SuspendAccountResponse")
    public SuspendAccountResponseModel suspendAccount(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        SuspendAccountRequestModel request)
        throws CustomerInfoServiceV1SuspendAccountBusinessFaultFaultFaultMessage, CustomerInfoServiceV1SuspendAccountSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.QueryCustomerStatusResponseModel
     * @throws CustomerInfoServiceV1QueryCustomerStatusSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1QueryCustomerStatusBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "QueryCustomerStatus", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/QueryCustomerStatus")
    @WebResult(name = "QueryCustomerStatusResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "QueryCustomerStatus", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.QueryCustomerStatus")
    @ResponseWrapper(localName = "QueryCustomerStatusResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.QueryCustomerStatusResponse")
    public QueryCustomerStatusResponseModel queryCustomerStatus(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        QueryCustomerStatusRequestModel request)
        throws CustomerInfoServiceV1QueryCustomerStatusBusinessFaultFaultFaultMessage, CustomerInfoServiceV1QueryCustomerStatusSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.QueryOpenOrdersForDevicesResponseModel
     * @throws CustomerInfoServiceV1QueryOpenOrdersForDevicesSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1QueryOpenOrdersForDevicesBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "QueryOpenOrdersForDevices", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/QueryOpenOrdersForDevices")
    @WebResult(name = "QueryOpenOrdersForDevicesResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "QueryOpenOrdersForDevices", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.QueryOpenOrdersForDevices")
    @ResponseWrapper(localName = "QueryOpenOrdersForDevicesResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.QueryOpenOrdersForDevicesResponse")
    public QueryOpenOrdersForDevicesResponseModel queryOpenOrdersForDevices(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        QueryOpenOrdersForDevicesRequestModel request)
        throws CustomerInfoServiceV1QueryOpenOrdersForDevicesBusinessFaultFaultFaultMessage, CustomerInfoServiceV1QueryOpenOrdersForDevicesSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ValidateAccountDeactivationResponseModel
     * @throws CustomerInfoServiceV1ValidateAccountDeactivationBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ValidateAccountDeactivationSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ValidateAccountDeactivation", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ValidateAccountDeactivation")
    @WebResult(name = "ValidateAccountDeactivationResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ValidateAccountDeactivation", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ValidateAccountDeactivation")
    @ResponseWrapper(localName = "ValidateAccountDeactivationResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ValidateAccountDeactivationResponse")
    public ValidateAccountDeactivationResponseModel validateAccountDeactivation(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ValidateAccountDeactivationRequestModel request)
        throws CustomerInfoServiceV1ValidateAccountDeactivationBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ValidateAccountDeactivationSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ReplaceStockInfoInContractResponseModel
     * @throws CustomerInfoServiceV1ReplaceStockInfoInContractSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ReplaceStockInfoInContractBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ReplaceStockInfoInContract", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ReplaceStockInfoInContract")
    @WebResult(name = "ReplaceStockInfoInContractResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ReplaceStockInfoInContract", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ReplaceStockInfoInContract")
    @ResponseWrapper(localName = "ReplaceStockInfoInContractResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ReplaceStockInfoInContractResponse")
    public ReplaceStockInfoInContractResponseModel replaceStockInfoInContract(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ReplaceStockInfoInContractRequestModel request)
        throws CustomerInfoServiceV1ReplaceStockInfoInContractBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ReplaceStockInfoInContractSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ReplaceStockInfoDeviceProductResponseModel
     * @throws CustomerInfoServiceV1ReplaceStockInfoDeviceProductBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ReplaceStockInfoDeviceProductSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ReplaceStockInfoDeviceProduct", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ReplaceStockInfoDeviceProduct")
    @WebResult(name = "ReplaceStockInfoDeviceProductResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ReplaceStockInfoDeviceProduct", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ReplaceStockInfoDeviceProduct")
    @ResponseWrapper(localName = "ReplaceStockInfoDeviceProductResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ReplaceStockInfoDeviceProductResponse")
    public ReplaceStockInfoDeviceProductResponseModel replaceStockInfoDeviceProduct(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ReplaceStockInfoDeviceProductRequestModel request)
        throws CustomerInfoServiceV1ReplaceStockInfoDeviceProductBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ReplaceStockInfoDeviceProductSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ReleaseNumbersOfVoipDeviceResponseModel
     * @throws CustomerInfoServiceV1ReleaseNumbersOfVoipDeviceBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ReleaseNumbersOfVoipDeviceSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ReleaseNumbersOfVoipDevice", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ReleaseNumbersOfVoipDevice")
    @WebResult(name = "ReleaseNumbersOfVoipDeviceResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ReleaseNumbersOfVoipDevice", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ReleaseNumbersOfVoipDevice")
    @ResponseWrapper(localName = "ReleaseNumbersOfVoipDeviceResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ReleaseNumbersOfVoipDeviceResponse")
    public ReleaseNumbersOfVoipDeviceResponseModel releaseNumbersOfVoipDevice(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ReleaseNumbersOfVoipDeviceRequestModel request)
        throws CustomerInfoServiceV1ReleaseNumbersOfVoipDeviceBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ReleaseNumbersOfVoipDeviceSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.AddNumbersToVoipDeviceResponseModel
     * @throws CustomerInfoServiceV1AddNumbersToVoipDeviceSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1AddNumbersToVoipDeviceBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddNumbersToVoipDevice", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/AddNumbersToVoipDevice")
    @WebResult(name = "AddNumbersToVoipDeviceResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "AddNumbersToVoipDevice", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AddNumbersToVoipDevice")
    @ResponseWrapper(localName = "AddNumbersToVoipDeviceResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AddNumbersToVoipDeviceResponse")
    public AddNumbersToVoipDeviceResponseModel addNumbersToVoipDevice(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        AddNumbersToVoipDeviceRequestModel request)
        throws CustomerInfoServiceV1AddNumbersToVoipDeviceBusinessFaultFaultFaultMessage, CustomerInfoServiceV1AddNumbersToVoipDeviceSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.RemoveVoipDeviceResponseModel
     * @throws CustomerInfoServiceV1RemoveVoipDeviceBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1RemoveVoipDeviceSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "RemoveVoipDevice", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/RemoveVoipDevice")
    @WebResult(name = "RemoveVoipDeviceResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "RemoveVoipDevice", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.RemoveVoipDevice")
    @ResponseWrapper(localName = "RemoveVoipDeviceResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.RemoveVoipDeviceResponse")
    public RemoveVoipDeviceResponseModel removeVoipDevice(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        RemoveVoipDeviceRequestModel request)
        throws CustomerInfoServiceV1RemoveVoipDeviceBusinessFaultFaultFaultMessage, CustomerInfoServiceV1RemoveVoipDeviceSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.GetBulutSantralNumbersByBillingContractNoResponseModel
     * @throws CustomerInfoServiceV1GetBulutSantralNumbersByBillingContractNoBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1GetBulutSantralNumbersByBillingContractNoSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetBulutSantralNumbersByBillingContractNo", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/GetBulutSantralNumbersByBillingContractNo")
    @WebResult(name = "GetBulutSantralNumbersByBillingContractNoResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "GetBulutSantralNumbersByBillingContractNo", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.GetBulutSantralNumbersByBillingContractNo")
    @ResponseWrapper(localName = "GetBulutSantralNumbersByBillingContractNoResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.GetBulutSantralNumbersByBillingContractNoResponse")
    public GetBulutSantralNumbersByBillingContractNoResponseModel getBulutSantralNumbersByBillingContractNo(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        GetBulutSantralNumbersByBillingContractNoRequestModel request)
        throws CustomerInfoServiceV1GetBulutSantralNumbersByBillingContractNoBusinessFaultFaultFaultMessage, CustomerInfoServiceV1GetBulutSantralNumbersByBillingContractNoSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.DummyJobResponse
     * @throws CustomerInfoServiceV1ProcessRetentionBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ProcessRetentionSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ProcessRetention", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ProcessRetention")
    @WebResult(name = "ProcessRetentionResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ProcessRetention", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ProcessRetention")
    @ResponseWrapper(localName = "ProcessRetentionResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ProcessRetentionResponse")
    public DummyJobResponse processRetention(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        DummyJobRequest request)
        throws CustomerInfoServiceV1ProcessRetentionBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ProcessRetentionSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.RemovePoolResponseModel
     * @throws CustomerInfoServiceV1RemovePoolBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1RemovePoolSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "RemovePool", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/RemovePool")
    @WebResult(name = "RemovePoolResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "RemovePool", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.RemovePool")
    @ResponseWrapper(localName = "RemovePoolResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.RemovePoolResponse")
    public RemovePoolResponseModel removePool(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        RemovePoolRequestModel request)
        throws CustomerInfoServiceV1RemovePoolBusinessFaultFaultFaultMessage, CustomerInfoServiceV1RemovePoolSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.RemovePoolItemsResponseModel
     * @throws CustomerInfoServiceV1RemovePoolItemsBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1RemovePoolItemsSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "RemovePoolItems", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/RemovePoolItems")
    @WebResult(name = "RemovePoolItemsResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "RemovePoolItems", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.RemovePoolItems")
    @ResponseWrapper(localName = "RemovePoolItemsResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.RemovePoolItemsResponse")
    public RemovePoolItemsResponseModel removePoolItems(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        RemovePoolItemsRequestModel request)
        throws CustomerInfoServiceV1RemovePoolItemsBusinessFaultFaultFaultMessage, CustomerInfoServiceV1RemovePoolItemsSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.AddPoolItemsResponseModel
     * @throws CustomerInfoServiceV1AddPoolItemsSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1AddPoolItemsBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddPoolItems", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/AddPoolItems")
    @WebResult(name = "AddPoolItemsResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "AddPoolItems", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AddPoolItems")
    @ResponseWrapper(localName = "AddPoolItemsResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AddPoolItemsResponse")
    public AddPoolItemsResponseModel addPoolItems(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        AddPoolItemsRequestModel request)
        throws CustomerInfoServiceV1AddPoolItemsBusinessFaultFaultFaultMessage, CustomerInfoServiceV1AddPoolItemsSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ProcessProcessRequestResponseModel
     * @throws CustomerInfoServiceV1ProcessRequestSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ProcessRequestBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ProcessRequest", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ProcessRequest")
    @WebResult(name = "ProcessRequestResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ProcessRequest", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ProcessRequest")
    @ResponseWrapper(localName = "ProcessRequestResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ProcessRequestResponse")
    public ProcessProcessRequestResponseModel processRequest(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ProcessProcessRequestRequestModel request)
        throws CustomerInfoServiceV1ProcessRequestBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ProcessRequestSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.CheckMillenifonGsmNumbersResponseModel
     * @throws CustomerInfoServiceV1CheckMillenifonGsmNumbersBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1CheckMillenifonGsmNumbersSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "CheckMillenifonGsmNumbers", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/CheckMillenifonGsmNumbers")
    @WebResult(name = "CheckMillenifonGsmNumbersResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "CheckMillenifonGsmNumbers", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.CheckMillenifonGsmNumbers")
    @ResponseWrapper(localName = "CheckMillenifonGsmNumbersResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.CheckMillenifonGsmNumbersResponse")
    public CheckMillenifonGsmNumbersResponseModel checkMillenifonGsmNumbers(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        CheckMillenifonGsmNumbersRequestModel request)
        throws CustomerInfoServiceV1CheckMillenifonGsmNumbersBusinessFaultFaultFaultMessage, CustomerInfoServiceV1CheckMillenifonGsmNumbersSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.AddMillenifonNumberResponseModel
     * @throws CustomerInfoServiceV1AddMillenifonNumberBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1AddMillenifonNumberSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddMillenifonNumber", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/AddMillenifonNumber")
    @WebResult(name = "AddMillenifonNumberResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "AddMillenifonNumber", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AddMillenifonNumber")
    @ResponseWrapper(localName = "AddMillenifonNumberResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AddMillenifonNumberResponse")
    public AddMillenifonNumberResponseModel addMillenifonNumber(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        AddMillenifonNumberRequestModel request)
        throws CustomerInfoServiceV1AddMillenifonNumberBusinessFaultFaultFaultMessage, CustomerInfoServiceV1AddMillenifonNumberSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.RemoveMillenifonNumberResponseModel
     * @throws CustomerInfoServiceV1RemoveMillenifonNumberSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1RemoveMillenifonNumberBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "RemoveMillenifonNumber", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/RemoveMillenifonNumber")
    @WebResult(name = "RemoveMillenifonNumberResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "RemoveMillenifonNumber", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.RemoveMillenifonNumber")
    @ResponseWrapper(localName = "RemoveMillenifonNumberResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.RemoveMillenifonNumberResponse")
    public RemoveMillenifonNumberResponseModel removeMillenifonNumber(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        RemoveMillenifonNumberRequestModel request)
        throws CustomerInfoServiceV1RemoveMillenifonNumberBusinessFaultFaultFaultMessage, CustomerInfoServiceV1RemoveMillenifonNumberSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.SellVoiceRecordResponseModel
     * @throws CustomerInfoServiceV1SellVoiceRecordSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1SellVoiceRecordBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SellVoiceRecord", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/SellVoiceRecord")
    @WebResult(name = "SellVoiceRecordResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "SellVoiceRecord", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.SellVoiceRecord")
    @ResponseWrapper(localName = "SellVoiceRecordResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.SellVoiceRecordResponse")
    public SellVoiceRecordResponseModel sellVoiceRecord(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        SellVoiceRecordRequestModel request)
        throws CustomerInfoServiceV1SellVoiceRecordBusinessFaultFaultFaultMessage, CustomerInfoServiceV1SellVoiceRecordSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param req
     * @throws CustomerInfoServiceV1AddItemToStockBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1AddItemToStockSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddItemToStock", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/AddItemToStock")
    @RequestWrapper(localName = "AddItemToStock", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AddItemToStock")
    @ResponseWrapper(localName = "AddItemToStockResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AddItemToStockResponse")
    public void addItemToStock(
        @WebParam(name = "req", targetNamespace = "/CustomerInfo/Service/v1")
        AddStockItemToStockRequestModel req)
        throws CustomerInfoServiceV1AddItemToStockBusinessFaultFaultFaultMessage, CustomerInfoServiceV1AddItemToStockSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.GetRemaingFreeUnitUsageByPhoneNumberResponseModel
     * @throws CustomerInfoServiceV1GetRemaingFreeUnitUsageByPhoneNumberSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1GetRemaingFreeUnitUsageByPhoneNumberBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetRemaingFreeUnitUsageByPhoneNumber", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/GetRemaingFreeUnitUsageByPhoneNumber")
    @WebResult(name = "GetRemaingFreeUnitUsageByPhoneNumberResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "GetRemaingFreeUnitUsageByPhoneNumber", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.GetRemaingFreeUnitUsageByPhoneNumber")
    @ResponseWrapper(localName = "GetRemaingFreeUnitUsageByPhoneNumberResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.GetRemaingFreeUnitUsageByPhoneNumberResponse")
    public GetRemaingFreeUnitUsageByPhoneNumberResponseModel getRemaingFreeUnitUsageByPhoneNumber(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        GetRemaingFreeUnitUsageByPhoneNumberRequestModel request)
        throws CustomerInfoServiceV1GetRemaingFreeUnitUsageByPhoneNumberBusinessFaultFaultFaultMessage, CustomerInfoServiceV1GetRemaingFreeUnitUsageByPhoneNumberSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.GetSaleAvailabilityResponseModel
     */
    @WebMethod(operationName = "GetSaleAvailability", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/GetSaleAvailability")
    @WebResult(name = "GetSaleAvailabilityResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "GetSaleAvailability", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.GetSaleAvailability")
    @ResponseWrapper(localName = "GetSaleAvailabilityResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.GetSaleAvailabilityResponse")
    public GetSaleAvailabilityResponseModel getSaleAvailability(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        GetSaleAvailabilityRequestModel request);

    /**
     * 
     * @param req
     * @return
     *     returns org.milleni.dunning.ws.client.crm.AddVoipDeviceWithProcessResponseModel
     * @throws CustomerInfoServiceV1AddVoipDeviceWithProcessBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1AddVoipDeviceWithProcessSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddVoipDeviceWithProcess", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/AddVoipDeviceWithProcess")
    @WebResult(name = "AddVoipDeviceWithProcessResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "AddVoipDeviceWithProcess", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AddVoipDeviceWithProcess")
    @ResponseWrapper(localName = "AddVoipDeviceWithProcessResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AddVoipDeviceWithProcessResponse")
    public AddVoipDeviceWithProcessResponseModel addVoipDeviceWithProcess(
        @WebParam(name = "req", targetNamespace = "/CustomerInfo/Service/v1")
        AddVoipDeviceWithProcessRequestModel req)
        throws CustomerInfoServiceV1AddVoipDeviceWithProcessBusinessFaultFaultFaultMessage, CustomerInfoServiceV1AddVoipDeviceWithProcessSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.CancelProcessResponseModel
     */
    @WebMethod(operationName = "CancelProcess", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/CancelProcess")
    @WebResult(name = "CancelProcessResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "CancelProcess", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.CancelProcess")
    @ResponseWrapper(localName = "CancelProcessResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.CancelProcessResponse")
    public CancelProcessResponseModel cancelProcess(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        CancelProcessRequestModel request);

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.GetDealerStokResponseModel
     * @throws CustomerInfoServiceV1GetDealerStocksBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1GetDealerStocksSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetDealerStocks", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/GetDealerStocks")
    @WebResult(name = "GetDealerStocksResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "GetDealerStocks", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.GetDealerStocks")
    @ResponseWrapper(localName = "GetDealerStocksResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.GetDealerStocksResponse")
    public GetDealerStokResponseModel getDealerStocks(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        GetDealerStokRequestModel request)
        throws CustomerInfoServiceV1GetDealerStocksBusinessFaultFaultFaultMessage, CustomerInfoServiceV1GetDealerStocksSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.UpdateDealerStokStatusResponseModel
     * @throws CustomerInfoServiceV1UpdateDealerStockStatusBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1UpdateDealerStockStatusSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateDealerStockStatus", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/UpdateDealerStockStatus")
    @WebResult(name = "UpdateDealerStockStatusResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "UpdateDealerStockStatus", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.UpdateDealerStockStatus")
    @ResponseWrapper(localName = "UpdateDealerStockStatusResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.UpdateDealerStockStatusResponse")
    public UpdateDealerStokStatusResponseModel updateDealerStockStatus(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        UpdateDealerStokStatusRequestModel request)
        throws CustomerInfoServiceV1UpdateDealerStockStatusBusinessFaultFaultFaultMessage, CustomerInfoServiceV1UpdateDealerStockStatusSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param processId
     * @throws CustomerInfoServiceV1ChangeTitleCreateProductSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ChangeTitleCreateProductBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ChangeTitleCreateProduct", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ChangeTitleCreateProduct")
    @RequestWrapper(localName = "ChangeTitleCreateProduct", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ChangeTitleCreateProduct")
    @ResponseWrapper(localName = "ChangeTitleCreateProductResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ChangeTitleCreateProductResponse")
    public void changeTitleCreateProduct(
        @WebParam(name = "processId", targetNamespace = "/CustomerInfo/Service/v1")
        String processId)
        throws CustomerInfoServiceV1ChangeTitleCreateProductBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ChangeTitleCreateProductSystemFaultFaultFaultMessage
    ;

}
