
package org.milleni.dunning.ws.client.crm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CustomerInfoServiceV1", targetNamespace = "/CustomerInfo/Service/v1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerInfoServiceV1 {


    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ProcessStaticIpRequestsResponseModel
     * @throws CustomerInfoServiceV1ProcessStaticIpRequestsSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ProcessStaticIpRequestsBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ProcessStaticIpRequests", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ProcessStaticIpRequests")
    @WebResult(name = "ProcessStaticIpRequestsResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ProcessStaticIpRequests", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ProcessStaticIpRequests")
    @ResponseWrapper(localName = "ProcessStaticIpRequestsResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ProcessStaticIpRequestsResponse")
    public ProcessStaticIpRequestsResponseModel processStaticIpRequests(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ProcessStaticIpRequestsRequestModel request)
        throws CustomerInfoServiceV1ProcessStaticIpRequestsBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ProcessStaticIpRequestsSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.MigratePartyResponseModel
     * @throws CustomerInfoServiceV1MigratePartySystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1MigratePartyBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "MigrateParty", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/MigrateParty")
    @WebResult(name = "MigratePartyResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "MigrateParty", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.MigrateParty")
    @ResponseWrapper(localName = "MigratePartyResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.MigratePartyResponse")
    public MigratePartyResponseModel migrateParty(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        MigratePartyRequestModel request)
        throws CustomerInfoServiceV1MigratePartyBusinessFaultFaultFaultMessage, CustomerInfoServiceV1MigratePartySystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.RemoveNumbersFromContractResponseModel
     * @throws CustomerInfoServiceV1RemoveNumbersFromContractBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1RemoveNumbersFromContractSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "RemoveNumbersFromContract", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/RemoveNumbersFromContract")
    @WebResult(name = "RemoveNumbersFromContractResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "RemoveNumbersFromContract", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.RemoveNumbersFromContract")
    @ResponseWrapper(localName = "RemoveNumbersFromContractResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.RemoveNumbersFromContractResponse")
    public RemoveNumbersFromContractResponseModel removeNumbersFromContract(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        RemoveNumbersFromContractRequestModel request)
        throws CustomerInfoServiceV1RemoveNumbersFromContractBusinessFaultFaultFaultMessage, CustomerInfoServiceV1RemoveNumbersFromContractSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.AddNumbersToContractResponseModel
     * @throws CustomerInfoServiceV1AddNumbersToContractBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1AddNumbersToContractSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddNumbersToContract", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/AddNumbersToContract")
    @WebResult(name = "AddNumbersToContractResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "AddNumbersToContract", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AddNumbersToContract")
    @ResponseWrapper(localName = "AddNumbersToContractResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AddNumbersToContractResponse")
    public AddNumbersToContractResponseModel addNumbersToContract(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        AddNumbersToContractRequestModel request)
        throws CustomerInfoServiceV1AddNumbersToContractBusinessFaultFaultFaultMessage, CustomerInfoServiceV1AddNumbersToContractSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.MigrateAccountResponseModel
     * @throws CustomerInfoServiceV1MigrateAccountSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1MigrateAccountBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "MigrateAccount", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/MigrateAccount")
    @WebResult(name = "MigrateAccountResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "MigrateAccount", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.MigrateAccount")
    @ResponseWrapper(localName = "MigrateAccountResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.MigrateAccountResponse")
    public MigrateAccountResponseModel migrateAccount(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        MigrateAccountRequestModel request)
        throws CustomerInfoServiceV1MigrateAccountBusinessFaultFaultFaultMessage, CustomerInfoServiceV1MigrateAccountSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.MigrateContractResponseModel
     * @throws CustomerInfoServiceV1MigrateContractSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1MigrateContractBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "MigrateContract", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/MigrateContract")
    @WebResult(name = "MigrateContractResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "MigrateContract", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.MigrateContract")
    @ResponseWrapper(localName = "MigrateContractResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.MigrateContractResponse")
    public MigrateContractResponseModel migrateContract(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        MigrateContractRequestModel request)
        throws CustomerInfoServiceV1MigrateContractBusinessFaultFaultFaultMessage, CustomerInfoServiceV1MigrateContractSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.RemoveDopingBoxProductResponseModel
     * @throws CustomerInfoServiceV1RemoveDopingBoxProductBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1RemoveDopingBoxProductSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "RemoveDopingBoxProduct", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/RemoveDopingBoxProduct")
    @WebResult(name = "RemoveDopingBoxProductResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "RemoveDopingBoxProduct", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.RemoveDopingBoxProduct")
    @ResponseWrapper(localName = "RemoveDopingBoxProductResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.RemoveDopingBoxProductResponse")
    public RemoveDopingBoxProductResponseModel removeDopingBoxProduct(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        RemoveDopingBoxProductRequestModel request)
        throws CustomerInfoServiceV1RemoveDopingBoxProductBusinessFaultFaultFaultMessage, CustomerInfoServiceV1RemoveDopingBoxProductSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.GetAccountPartyCodeResponseModel
     * @throws CustomerInfoServiceV1GetAccountPartyCodeBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1GetAccountPartyCodeSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetAccountPartyCode", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/GetAccountPartyCode")
    @WebResult(name = "GetAccountPartyCodeResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "GetAccountPartyCode", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.GetAccountPartyCode")
    @ResponseWrapper(localName = "GetAccountPartyCodeResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.GetAccountPartyCodeResponse")
    public GetAccountPartyCodeResponseModel getAccountPartyCode(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        GetAccountPartyCodeRequestModel request)
        throws CustomerInfoServiceV1GetAccountPartyCodeBusinessFaultFaultFaultMessage, CustomerInfoServiceV1GetAccountPartyCodeSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ActivateAccountResponseModel
     * @throws CustomerInfoServiceV1ActivateAccountBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ActivateAccountSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ActivateAccount", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ActivateAccount")
    @WebResult(name = "ActivateAccountResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ActivateAccount", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ActivateAccount")
    @ResponseWrapper(localName = "ActivateAccountResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ActivateAccountResponse")
    public ActivateAccountResponseModel activateAccount(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ActivateAccountRequestModel request)
        throws CustomerInfoServiceV1ActivateAccountBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ActivateAccountSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.SuspendAccountResponseModel
     * @throws CustomerInfoServiceV1SuspendAccountBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1SuspendAccountSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SuspendAccount", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/SuspendAccount")
    @WebResult(name = "SuspendAccountResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "SuspendAccount", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.SuspendAccount")
    @ResponseWrapper(localName = "SuspendAccountResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.SuspendAccountResponse")
    public SuspendAccountResponseModel suspendAccount(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        SuspendAccountRequestModel request)
        throws CustomerInfoServiceV1SuspendAccountBusinessFaultFaultFaultMessage, CustomerInfoServiceV1SuspendAccountSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.DeactivateAccountResponseModel
     * @throws CustomerInfoServiceV1DeactivateAccountSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1DeactivateAccountBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "DeactivateAccount", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/DeactivateAccount")
    @WebResult(name = "DeactivateAccountResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "DeactivateAccount", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.DeactivateAccount")
    @ResponseWrapper(localName = "DeactivateAccountResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.DeactivateAccountResponse")
    public DeactivateAccountResponseModel deactivateAccount(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        DeactivateAccountRequestModel request)
        throws CustomerInfoServiceV1DeactivateAccountBusinessFaultFaultFaultMessage, CustomerInfoServiceV1DeactivateAccountSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.QueryCustomerResponseModel
     * @throws CustomerInfoServiceV1QueryCustomerSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1QueryCustomerBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "QueryCustomer", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/QueryCustomer")
    @WebResult(name = "QueryCustomerResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "QueryCustomer", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.QueryCustomer")
    @ResponseWrapper(localName = "QueryCustomerResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.QueryCustomerResponse")
    public QueryCustomerResponseModel queryCustomer(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        QueryCustomerRequestModel request)
        throws CustomerInfoServiceV1QueryCustomerBusinessFaultFaultFaultMessage, CustomerInfoServiceV1QueryCustomerSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.GetCustomerResponseModel
     * @throws CustomerInfoServiceV1GetCustomerBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1GetCustomerSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCustomer", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/GetCustomer")
    @WebResult(name = "GetCustomerResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "GetCustomer", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.GetCustomer")
    @ResponseWrapper(localName = "GetCustomerResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.GetCustomerResponse")
    public GetCustomerResponseModel getCustomer(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        GetCustomerRequestModel request)
        throws CustomerInfoServiceV1GetCustomerBusinessFaultFaultFaultMessage, CustomerInfoServiceV1GetCustomerSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.GetCustomerResponseModel
     * @throws CustomerInfoServiceV1GetCustomerByCustomerIdBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1GetCustomerByCustomerIdSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCustomerByCustomerId", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/GetCustomerByCustomerId")
    @WebResult(name = "GetCustomerByCustomerIdResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "GetCustomerByCustomerId", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.GetCustomerByCustomerId")
    @ResponseWrapper(localName = "GetCustomerByCustomerIdResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.GetCustomerByCustomerIdResponse")
    public GetCustomerResponseModel getCustomerByCustomerId(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        GetCustomerRequestModel request)
        throws CustomerInfoServiceV1GetCustomerByCustomerIdBusinessFaultFaultFaultMessage, CustomerInfoServiceV1GetCustomerByCustomerIdSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.UserResponseModel
     * @throws CustomerInfoServiceV1AddUserSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1AddUserBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddUser", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/AddUser")
    @WebResult(name = "AddUserResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "AddUser", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AddUser")
    @ResponseWrapper(localName = "AddUserResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AddUserResponse")
    public UserResponseModel addUser(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        UserRequestModel request)
        throws CustomerInfoServiceV1AddUserBusinessFaultFaultFaultMessage, CustomerInfoServiceV1AddUserSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.UserResponseModel
     * @throws CustomerInfoServiceV1UpdateUserBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1UpdateUserSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateUser", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/UpdateUser")
    @WebResult(name = "UpdateUserResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "UpdateUser", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.UpdateUser")
    @ResponseWrapper(localName = "UpdateUserResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.UpdateUserResponse")
    public UserResponseModel updateUser(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        UserRequestModel request)
        throws CustomerInfoServiceV1UpdateUserBusinessFaultFaultFaultMessage, CustomerInfoServiceV1UpdateUserSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.UserResponseModel
     * @throws CustomerInfoServiceV1DeleteUserBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1DeleteUserSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "DeleteUser", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/DeleteUser")
    @WebResult(name = "DeleteUserResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "DeleteUser", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.DeleteUser")
    @ResponseWrapper(localName = "DeleteUserResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.DeleteUserResponse")
    public UserResponseModel deleteUser(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        UserRequestModel request)
        throws CustomerInfoServiceV1DeleteUserBusinessFaultFaultFaultMessage, CustomerInfoServiceV1DeleteUserSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.GetPartnerResponseModel
     * @throws CustomerInfoServiceV1GetPartnerSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1GetPartnerBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetPartner", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/GetPartner")
    @WebResult(name = "GetPartnerResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "GetPartner", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.GetPartner")
    @ResponseWrapper(localName = "GetPartnerResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.GetPartnerResponse")
    public GetPartnerResponseModel getPartner(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        GetPartnerRequestModel request)
        throws CustomerInfoServiceV1GetPartnerBusinessFaultFaultFaultMessage, CustomerInfoServiceV1GetPartnerSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.QueryStockItemResponseModel
     * @throws CustomerInfoServiceV1QueryStockItemSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1QueryStockItemBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "QueryStockItem", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/QueryStockItem")
    @WebResult(name = "QueryStockItemResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "QueryStockItem", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.QueryStockItem")
    @ResponseWrapper(localName = "QueryStockItemResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.QueryStockItemResponse")
    public QueryStockItemResponseModel queryStockItem(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        QueryStockItemRequestModel request)
        throws CustomerInfoServiceV1QueryStockItemBusinessFaultFaultFaultMessage, CustomerInfoServiceV1QueryStockItemSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.QueryStockItemOuidResponseModel
     * @throws CustomerInfoServiceV1QueryStockItemOuidBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1QueryStockItemOuidSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "QueryStockItemOuid", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/QueryStockItemOuid")
    @WebResult(name = "QueryStockItemOuidResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "QueryStockItemOuid", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.QueryStockItemOuid")
    @ResponseWrapper(localName = "QueryStockItemOuidResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.QueryStockItemOuidResponse")
    public QueryStockItemOuidResponseModel queryStockItemOuid(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        QueryStockItemOuidRequestModel request)
        throws CustomerInfoServiceV1QueryStockItemOuidBusinessFaultFaultFaultMessage, CustomerInfoServiceV1QueryStockItemOuidSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ChangeStockItemStatusResponseModel
     * @throws CustomerInfoServiceV1ReserveStockItemBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ReserveStockItemSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ReserveStockItem", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ReserveStockItem")
    @WebResult(name = "ReserveStockItemResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ReserveStockItem", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ReserveStockItem")
    @ResponseWrapper(localName = "ReserveStockItemResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ReserveStockItemResponse")
    public ChangeStockItemStatusResponseModel reserveStockItem(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ReserveStockItemRequestModel request)
        throws CustomerInfoServiceV1ReserveStockItemBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ReserveStockItemSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ChangeStockItemStatusResponseModel
     * @throws CustomerInfoServiceV1AssignStockItemSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1AssignStockItemBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AssignStockItem", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/AssignStockItem")
    @WebResult(name = "AssignStockItemResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "AssignStockItem", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AssignStockItem")
    @ResponseWrapper(localName = "AssignStockItemResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AssignStockItemResponse")
    public ChangeStockItemStatusResponseModel assignStockItem(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        AssignStockItemRequestModel request)
        throws CustomerInfoServiceV1AssignStockItemBusinessFaultFaultFaultMessage, CustomerInfoServiceV1AssignStockItemSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ChangeStockItemStatusResponseModel
     * @throws CustomerInfoServiceV1ReleaseStockItemSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ReleaseStockItemBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ReleaseStockItem", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ReleaseStockItem")
    @WebResult(name = "ReleaseStockItemResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ReleaseStockItem", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ReleaseStockItem")
    @ResponseWrapper(localName = "ReleaseStockItemResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ReleaseStockItemResponse")
    public ChangeStockItemStatusResponseModel releaseStockItem(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ReleaseStockItemRequestModel request)
        throws CustomerInfoServiceV1ReleaseStockItemBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ReleaseStockItemSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.CRMProvisionResponseModel
     * @throws CustomerInfoServiceV1ProvisionOrderToCRMBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ProvisionOrderToCRMSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ProvisionOrderToCRM", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ProvisionOrderToCRM")
    @WebResult(name = "ProvisionOrderToCRMResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ProvisionOrderToCRM", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ProvisionOrderToCRM")
    @ResponseWrapper(localName = "ProvisionOrderToCRMResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ProvisionOrderToCRMResponse")
    public CRMProvisionResponseModel provisionOrderToCRM(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        CRMProvisionRequestModel request)
        throws CustomerInfoServiceV1ProvisionOrderToCRMBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ProvisionOrderToCRMSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.GetNumbersFromPoolResponseModel
     * @throws CustomerInfoServiceV1GetNumbersFromPoolBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1GetNumbersFromPoolSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetNumbersFromPool", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/GetNumbersFromPool")
    @WebResult(name = "GetNumbersFromPoolResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "GetNumbersFromPool", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.GetNumbersFromPool")
    @ResponseWrapper(localName = "GetNumbersFromPoolResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.GetNumbersFromPoolResponse")
    public GetNumbersFromPoolResponseModel getNumbersFromPool(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        GetNumbersFromPoolRequestModel request)
        throws CustomerInfoServiceV1GetNumbersFromPoolBusinessFaultFaultFaultMessage, CustomerInfoServiceV1GetNumbersFromPoolSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.QueryNumberPoolItemResponseModel
     * @throws CustomerInfoServiceV1QueryNumberPoolItemSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1QueryNumberPoolItemBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "QueryNumberPoolItem", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/QueryNumberPoolItem")
    @WebResult(name = "QueryNumberPoolItemResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "QueryNumberPoolItem", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.QueryNumberPoolItem")
    @ResponseWrapper(localName = "QueryNumberPoolItemResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.QueryNumberPoolItemResponse")
    public QueryNumberPoolItemResponseModel queryNumberPoolItem(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        QueryNumberPoolItemRequestModel request)
        throws CustomerInfoServiceV1QueryNumberPoolItemBusinessFaultFaultFaultMessage, CustomerInfoServiceV1QueryNumberPoolItemSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ChangeNumberPoolItemStatusResponseModel
     * @throws CustomerInfoServiceV1ReserveNumberPoolItemBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ReserveNumberPoolItemSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ReserveNumberPoolItem", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ReserveNumberPoolItem")
    @WebResult(name = "ReserveNumberPoolItemResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ReserveNumberPoolItem", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ReserveNumberPoolItem")
    @ResponseWrapper(localName = "ReserveNumberPoolItemResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ReserveNumberPoolItemResponse")
    public ChangeNumberPoolItemStatusResponseModel reserveNumberPoolItem(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ReserveNumberPoolItemRequestModel request)
        throws CustomerInfoServiceV1ReserveNumberPoolItemBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ReserveNumberPoolItemSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ChangeNumberPoolItemStatusResponseModel
     * @throws CustomerInfoServiceV1AssignNumberPoolItemSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1AssignNumberPoolItemBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AssignNumberPoolItem", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/AssignNumberPoolItem")
    @WebResult(name = "AssignNumberPoolItemResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "AssignNumberPoolItem", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AssignNumberPoolItem")
    @ResponseWrapper(localName = "AssignNumberPoolItemResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.AssignNumberPoolItemResponse")
    public ChangeNumberPoolItemStatusResponseModel assignNumberPoolItem(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        AssignNumberPoolItemRequestModel request)
        throws CustomerInfoServiceV1AssignNumberPoolItemBusinessFaultFaultFaultMessage, CustomerInfoServiceV1AssignNumberPoolItemSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ChangeNumberPoolItemStatusResponseModel
     * @throws CustomerInfoServiceV1ReleaseNumberPoolItemBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ReleaseNumberPoolItemSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ReleaseNumberPoolItem", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ReleaseNumberPoolItem")
    @WebResult(name = "ReleaseNumberPoolItemResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ReleaseNumberPoolItem", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ReleaseNumberPoolItem")
    @ResponseWrapper(localName = "ReleaseNumberPoolItemResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ReleaseNumberPoolItemResponse")
    public ChangeNumberPoolItemStatusResponseModel releaseNumberPoolItem(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ReleaseNumberPoolItemRequestModel request)
        throws CustomerInfoServiceV1ReleaseNumberPoolItemBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ReleaseNumberPoolItemSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ChangeNumberPoolItemStatusResponseModel
     * @throws CustomerInfoServiceV1BlockNumberPoolItemBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1BlockNumberPoolItemSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BlockNumberPoolItem", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/BlockNumberPoolItem")
    @WebResult(name = "BlockNumberPoolItemResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "BlockNumberPoolItem", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.BlockNumberPoolItem")
    @ResponseWrapper(localName = "BlockNumberPoolItemResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.BlockNumberPoolItemResponse")
    public ChangeNumberPoolItemStatusResponseModel blockNumberPoolItem(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        BlockNumberPoolItemRequestModel request)
        throws CustomerInfoServiceV1BlockNumberPoolItemBusinessFaultFaultFaultMessage, CustomerInfoServiceV1BlockNumberPoolItemSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ChangeNumberPoolItemStatusResponseModel
     * @throws CustomerInfoServiceV1UnavailableNumberPoolItemBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1UnavailableNumberPoolItemSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UnavailableNumberPoolItem", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/UnavailableNumberPoolItem")
    @WebResult(name = "UnavailableNumberPoolItemResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "UnavailableNumberPoolItem", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.UnavailableNumberPoolItem")
    @ResponseWrapper(localName = "UnavailableNumberPoolItemResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.UnavailableNumberPoolItemResponse")
    public ChangeNumberPoolItemStatusResponseModel unavailableNumberPoolItem(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        UnavailableNumberPoolItemRequestModel request)
        throws CustomerInfoServiceV1UnavailableNumberPoolItemBusinessFaultFaultFaultMessage, CustomerInfoServiceV1UnavailableNumberPoolItemSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.DeactivateCustomerContractResponseModel
     * @throws CustomerInfoServiceV1DeactivateCustomerContractSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1DeactivateCustomerContractBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "DeactivateCustomerContract", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/DeactivateCustomerContract")
    @WebResult(name = "DeactivateCustomerContractResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "DeactivateCustomerContract", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.DeactivateCustomerContract")
    @ResponseWrapper(localName = "DeactivateCustomerContractResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.DeactivateCustomerContractResponse")
    public DeactivateCustomerContractResponseModel deactivateCustomerContract(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        DeactivateCustomerContractRequestModel request)
        throws CustomerInfoServiceV1DeactivateCustomerContractBusinessFaultFaultFaultMessage, CustomerInfoServiceV1DeactivateCustomerContractSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.SuspendCustomerContractResponseModel
     * @throws CustomerInfoServiceV1SuspendCustomerContractBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1SuspendCustomerContractSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SuspendCustomerContract", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/SuspendCustomerContract")
    @WebResult(name = "SuspendCustomerContractResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "SuspendCustomerContract", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.SuspendCustomerContract")
    @ResponseWrapper(localName = "SuspendCustomerContractResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.SuspendCustomerContractResponse")
    public SuspendCustomerContractResponseModel suspendCustomerContract(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        SuspendCustomerContractRequestModel request)
        throws CustomerInfoServiceV1SuspendCustomerContractBusinessFaultFaultFaultMessage, CustomerInfoServiceV1SuspendCustomerContractSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ActivateCustomerContractResponseModel
     * @throws CustomerInfoServiceV1ActivateCustomerContractBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ActivateCustomerContractSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ActivateCustomerContract", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ActivateCustomerContract")
    @WebResult(name = "ActivateCustomerContractResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ActivateCustomerContract", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ActivateCustomerContract")
    @ResponseWrapper(localName = "ActivateCustomerContractResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ActivateCustomerContractResponse")
    public ActivateCustomerContractResponseModel activateCustomerContract(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ActivateCustomerContractRequestModel request)
        throws CustomerInfoServiceV1ActivateCustomerContractBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ActivateCustomerContractSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ProcessChurnContractsResponseModel
     * @throws CustomerInfoServiceV1ProcessChurnContractsBusinessFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ProcessChurnContractsSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ProcessChurnContracts", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ProcessChurnContracts")
    @WebResult(name = "ProcessChurnContractsResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ProcessChurnContracts", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ProcessChurnContracts")
    @ResponseWrapper(localName = "ProcessChurnContractsResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ProcessChurnContractsResponse")
    public ProcessChurnContractsResponseModel processChurnContracts(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ProcessChurnContractsRequestModel request)
        throws CustomerInfoServiceV1ProcessChurnContractsBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ProcessChurnContractsSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crm.ProcessSuspendedContractsResponseModel
     * @throws CustomerInfoServiceV1ProcessSuspendedContractsSystemFaultFaultFaultMessage
     * @throws CustomerInfoServiceV1ProcessSuspendedContractsBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ProcessSuspendedContracts", action = "/CustomerInfo/Service/v1/CustomerInfoServiceV1/ProcessSuspendedContracts")
    @WebResult(name = "ProcessSuspendedContractsResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ProcessSuspendedContracts", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ProcessSuspendedContracts")
    @ResponseWrapper(localName = "ProcessSuspendedContractsResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crm.ProcessSuspendedContractsResponse")
    public ProcessSuspendedContractsResponseModel processSuspendedContracts(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ProcessSuspendedContractsRequestModel request)
        throws CustomerInfoServiceV1ProcessSuspendedContractsBusinessFaultFaultFaultMessage, CustomerInfoServiceV1ProcessSuspendedContractsSystemFaultFaultFaultMessage
    ;

}
