
package org.milleni.dunning.ws.client.callcenter;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CallCenterNotificationOperations", targetNamespace = "http://milleni.com.tr/CallCenterNotificationOperations", wsdlLocation = "http://localhost:1140/CallCenterNotificationOperations.asmx?WSDL")
public class CallCenterNotificationOperations
    extends Service
{

    private final static URL CALLCENTERNOTIFICATIONOPERATIONS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.milleni.dunning.ws.client.callcenter.CallCenterNotificationOperations.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.milleni.dunning.ws.client.callcenter.CallCenterNotificationOperations.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:1140/CallCenterNotificationOperations.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:1140/CallCenterNotificationOperations.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CALLCENTERNOTIFICATIONOPERATIONS_WSDL_LOCATION = url;
    }

    public CallCenterNotificationOperations(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CallCenterNotificationOperations() {
        super(CALLCENTERNOTIFICATIONOPERATIONS_WSDL_LOCATION, new QName("http://milleni.com.tr/CallCenterNotificationOperations", "CallCenterNotificationOperations"));
    }

    /**
     * 
     * @return
     *     returns CallCenterNotificationOperationsSoap
     */
    @WebEndpoint(name = "CallCenterNotificationOperationsSoap")
    public CallCenterNotificationOperationsSoap getCallCenterNotificationOperationsSoap() {
        return super.getPort(new QName("http://milleni.com.tr/CallCenterNotificationOperations", "CallCenterNotificationOperationsSoap"), CallCenterNotificationOperationsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CallCenterNotificationOperationsSoap
     */
    @WebEndpoint(name = "CallCenterNotificationOperationsSoap")
    public CallCenterNotificationOperationsSoap getCallCenterNotificationOperationsSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://milleni.com.tr/CallCenterNotificationOperations", "CallCenterNotificationOperationsSoap"), CallCenterNotificationOperationsSoap.class, features);
    }

}
