
package org.milleni.dunning.ws.client.callcenter;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CallCenterNotificationOperationsSoap", targetNamespace = "http://milleni.com.tr/CallCenterNotificationOperations")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CallCenterNotificationOperationsSoap {


    /**
     * 
     * @param guid
     * @param customerId
     * @param invoiceList
     * @param callType
     * @return
     *     returns org.milleni.dunning.ws.client.callcenter.ServiceResponse
     */
    @WebMethod(action = "http://milleni.com.tr/CallCenterNotificationOperations/callCenterInform")
    @WebResult(name = "callCenterInformResult", targetNamespace = "http://milleni.com.tr/CallCenterNotificationOperations")
    @RequestWrapper(localName = "callCenterInform", targetNamespace = "http://milleni.com.tr/CallCenterNotificationOperations", className = "org.milleni.dunning.ws.client.callcenter.CallCenterInform")
    @ResponseWrapper(localName = "callCenterInformResponse", targetNamespace = "http://milleni.com.tr/CallCenterNotificationOperations", className = "org.milleni.dunning.ws.client.callcenter.CallCenterInformResponse")
    public ServiceResponse callCenterInform(
        @WebParam(name = "guid", targetNamespace = "http://milleni.com.tr/CallCenterNotificationOperations")
        String guid,
        @WebParam(name = "callType", targetNamespace = "http://milleni.com.tr/CallCenterNotificationOperations")
        CallType callType,
        @WebParam(name = "customerId", targetNamespace = "http://milleni.com.tr/CallCenterNotificationOperations")
        long customerId,
        @WebParam(name = "invoiceList", targetNamespace = "http://milleni.com.tr/CallCenterNotificationOperations")
        ArrayOfInvoice invoiceList);

}
