
package org.milleni.dunning.ws.client.notif;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "INotificationServiceV1", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface INotificationServiceV1 {


    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.notif.SendSmsResponseModel
     * @throws INotificationServiceV1SendSmsBusinessFaultFaultFaultMessage
     * @throws INotificationServiceV1SendSmsSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SendSms", action = "http://tempuri.org/INotificationServiceV1/SendSms")
    @WebResult(name = "SendSmsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendSms", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.notif.SendSms")
    @ResponseWrapper(localName = "SendSmsResponse", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.notif.SendSmsResponse")
    public SendSmsResponseModel sendSms(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        SendSmsRequestModel request)
        throws INotificationServiceV1SendSmsBusinessFaultFaultFaultMessage, INotificationServiceV1SendSmsSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.notif.SendFutureSmsResponseModel
     * @throws INotificationServiceV1SendFutureSmsSystemFaultFaultFaultMessage
     * @throws INotificationServiceV1SendFutureSmsBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SendFutureSms", action = "http://tempuri.org/INotificationServiceV1/SendFutureSms")
    @WebResult(name = "SendFutureSmsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendFutureSms", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.notif.SendFutureSms")
    @ResponseWrapper(localName = "SendFutureSmsResponse", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.notif.SendFutureSmsResponse")
    public SendFutureSmsResponseModel sendFutureSms(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        SendFutureSmsRequestModel request)
        throws INotificationServiceV1SendFutureSmsBusinessFaultFaultFaultMessage, INotificationServiceV1SendFutureSmsSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.notif.SendEmailResponseModel
     * @throws INotificationServiceV1SendEmailSystemFaultFaultFaultMessage
     * @throws INotificationServiceV1SendEmailBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SendEmail", action = "http://tempuri.org/INotificationServiceV1/SendEmail")
    @WebResult(name = "SendEmailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendEmail", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.notif.SendEmail")
    @ResponseWrapper(localName = "SendEmailResponse", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.notif.SendEmailResponse")
    public SendEmailResponseModel sendEmail(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        SendEmailRequestModel request)
        throws INotificationServiceV1SendEmailBusinessFaultFaultFaultMessage, INotificationServiceV1SendEmailSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.notif.GetSmsLogResponseModel
     * @throws INotificationServiceV1GetSmsLogBusinessFaultFaultFaultMessage
     * @throws INotificationServiceV1GetSmsLogSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetSmsLog", action = "http://tempuri.org/INotificationServiceV1/GetSmsLog")
    @WebResult(name = "GetSmsLogResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSmsLog", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.notif.GetSmsLog")
    @ResponseWrapper(localName = "GetSmsLogResponse", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.notif.GetSmsLogResponse")
    public GetSmsLogResponseModel getSmsLog(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        GetSmsLogRequestModel request)
        throws INotificationServiceV1GetSmsLogBusinessFaultFaultFaultMessage, INotificationServiceV1GetSmsLogSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.notif.SendImediateSmsToCustomerResponseModel
     * @throws INotificationServiceV1SendImediateSmsToCustomerBusinessFaultFaultFaultMessage
     * @throws INotificationServiceV1SendImediateSmsToCustomerSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SendImediateSmsToCustomer", action = "http://tempuri.org/INotificationServiceV1/SendImediateSmsToCustomer")
    @WebResult(name = "SendImediateSmsToCustomerResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendImediateSmsToCustomer", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.notif.SendImediateSmsToCustomer")
    @ResponseWrapper(localName = "SendImediateSmsToCustomerResponse", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.notif.SendImediateSmsToCustomerResponse")
    public SendImediateSmsToCustomerResponseModel sendImediateSmsToCustomer(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        SendImediateSmsToCustomerRequestModel request)
        throws INotificationServiceV1SendImediateSmsToCustomerBusinessFaultFaultFaultMessage, INotificationServiceV1SendImediateSmsToCustomerSystemFaultFaultFaultMessage
    ;

}
