
package org.milleni.dunning.ws.client.notif;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "NotificationServiceV1", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://192.168.2.88:8230/NotificationService/NotificationServiceV1.svc?singleWsdl")
public class NotificationServiceV1
    extends Service
{

    private final static URL NOTIFICATIONSERVICEV1_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.milleni.dunning.ws.client.notif.NotificationServiceV1 .class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.milleni.dunning.ws.client.notif.NotificationServiceV1 .class.getResource(".");
            url = new URL(baseUrl, "http://192.168.2.88:8230/NotificationService/NotificationServiceV1.svc?singleWsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.2.88:8230/NotificationService/NotificationServiceV1.svc?singleWsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        NOTIFICATIONSERVICEV1_WSDL_LOCATION = url;
    }

    public NotificationServiceV1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotificationServiceV1() {
        super(NOTIFICATIONSERVICEV1_WSDL_LOCATION, new QName("http://tempuri.org/", "NotificationServiceV1"));
    }

    /**
     * 
     * @return
     *     returns INotificationServiceV1
     */
    @WebEndpoint(name = "BasicHttpBinding_INotificationServiceV1")
    public INotificationServiceV1 getBasicHttpBindingINotificationServiceV1() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_INotificationServiceV1"), INotificationServiceV1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns INotificationServiceV1
     */
    @WebEndpoint(name = "BasicHttpBinding_INotificationServiceV1")
    public INotificationServiceV1 getBasicHttpBindingINotificationServiceV1(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_INotificationServiceV1"), INotificationServiceV1.class, features);
    }

}
