
package org.milleni.dunning.ws.client.crmaccountcoa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AccountServiceV1", targetNamespace = "/CustomerInfo/Service/v1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccountServiceV1 {


    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crmaccountcoa.UpdateContactInfoResponseModel
     */
    @WebMethod(operationName = "UpdateContactInfo", action = "/CustomerInfo/Service/v1/AccountServiceV1/UpdateContactInfo")
    @WebResult(name = "UpdateContactInfoResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "UpdateContactInfo", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.UpdateContactInfo")
    @ResponseWrapper(localName = "UpdateContactInfoResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.UpdateContactInfoResponse")
    public UpdateContactInfoResponseModel updateContactInfo(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        UpdateContactInfoRequestModel request);

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crmaccountcoa.AddCreditCardOrderResponseModel
     */
    @WebMethod(operationName = "AddCreditCardOrder", action = "/CustomerInfo/Service/v1/AccountServiceV1/AddCreditCardOrder")
    @WebResult(name = "AddCreditCardOrderResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "AddCreditCardOrder", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.AddCreditCardOrder")
    @ResponseWrapper(localName = "AddCreditCardOrderResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.AddCreditCardOrderResponse")
    public AddCreditCardOrderResponseModel addCreditCardOrder(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        AddCreditCardOrderRequestModel request);

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crmaccountcoa.RemoveCreditCardOrderResponseModel
     */
    @WebMethod(operationName = "RemoveCreditCardOrder", action = "/CustomerInfo/Service/v1/AccountServiceV1/RemoveCreditCardOrder")
    @WebResult(name = "RemoveCreditCardOrderResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "RemoveCreditCardOrder", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.RemoveCreditCardOrder")
    @ResponseWrapper(localName = "RemoveCreditCardOrderResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.RemoveCreditCardOrderResponse")
    public RemoveCreditCardOrderResponseModel removeCreditCardOrder(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        RemoveCreditCardOrderRequestModel request);

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crmaccountcoa.ChangeBillingAddressResponseModel
     */
    @WebMethod(operationName = "ChangeBillingAddress", action = "/CustomerInfo/Service/v1/AccountServiceV1/ChangeBillingAddress")
    @WebResult(name = "ChangeBillingAddressResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ChangeBillingAddress", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.ChangeBillingAddress")
    @ResponseWrapper(localName = "ChangeBillingAddressResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.ChangeBillingAddressResponse")
    public ChangeBillingAddressResponseModel changeBillingAddress(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ChangeBillingAddressRequestModel request);

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crmaccountcoa.GetCreditCardOrderResponseModel
     */
    @WebMethod(operationName = "GetCreditCardOrder", action = "/CustomerInfo/Service/v1/AccountServiceV1/GetCreditCardOrder")
    @WebResult(name = "GetCreditCardOrderResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "GetCreditCardOrder", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.GetCreditCardOrder")
    @ResponseWrapper(localName = "GetCreditCardOrderResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.GetCreditCardOrderResponse")
    public GetCreditCardOrderResponseModel getCreditCardOrder(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        GetCreditCardOrderRequestModel request);

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crmaccountcoa.GetCreditCardOrderHistoryResponseModel
     * @throws AccountServiceV1GetCreditCardOrderHistorySystemFaultFaultFaultMessage
     * @throws AccountServiceV1GetCreditCardOrderHistoryBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCreditCardOrderHistory", action = "/CustomerInfo/Service/v1/AccountServiceV1/GetCreditCardOrderHistory")
    @WebResult(name = "GetCreditCardOrderHistoryResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "GetCreditCardOrderHistory", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.GetCreditCardOrderHistory")
    @ResponseWrapper(localName = "GetCreditCardOrderHistoryResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.GetCreditCardOrderHistoryResponse")
    public GetCreditCardOrderHistoryResponseModel getCreditCardOrderHistory(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        GetCreditCardOrderHistoryRequestModel request)
        throws AccountServiceV1GetCreditCardOrderHistoryBusinessFaultFaultFaultMessage, AccountServiceV1GetCreditCardOrderHistorySystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param req
     * @return
     *     returns org.milleni.dunning.ws.client.crmaccountcoa.SendAnnounceByBillingCustomerNoResponseModel
     * @throws AccountServiceV1SendIhtarAnnounceByBillingCustomerIdSystemFaultFaultFaultMessage
     * @throws AccountServiceV1SendIhtarAnnounceByBillingCustomerIdBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SendIhtarAnnounceByBillingCustomerId", action = "/CustomerInfo/Service/v1/AccountServiceV1/SendIhtarAnnounceByBillingCustomerId")
    @WebResult(name = "SendIhtarAnnounceByBillingCustomerIdResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "SendIhtarAnnounceByBillingCustomerId", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.SendIhtarAnnounceByBillingCustomerId")
    @ResponseWrapper(localName = "SendIhtarAnnounceByBillingCustomerIdResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.SendIhtarAnnounceByBillingCustomerIdResponse")
    public SendAnnounceByBillingCustomerNoResponseModel sendIhtarAnnounceByBillingCustomerId(
        @WebParam(name = "req", targetNamespace = "/CustomerInfo/Service/v1")
        SendAnnounceByBillingCustomerNoRequestModel req)
        throws AccountServiceV1SendIhtarAnnounceByBillingCustomerIdBusinessFaultFaultFaultMessage, AccountServiceV1SendIhtarAnnounceByBillingCustomerIdSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crmaccountcoa.AddProcessResponseModel
     * @throws AccountServiceV1AddDeactivationRequestBusinessFaultFaultFaultMessage
     * @throws AccountServiceV1AddDeactivationRequestSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddDeactivationRequest", action = "/CustomerInfo/Service/v1/AccountServiceV1/AddDeactivationRequest")
    @WebResult(name = "AddDeactivationRequestResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "AddDeactivationRequest", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.AddDeactivationRequest")
    @ResponseWrapper(localName = "AddDeactivationRequestResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.AddDeactivationRequestResponse")
    public AddProcessResponseModel addDeactivationRequest(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        AddDeactivationRequestToAccountRequestModel request)
        throws AccountServiceV1AddDeactivationRequestBusinessFaultFaultFaultMessage, AccountServiceV1AddDeactivationRequestSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crmaccountcoa.AddSoftInvoiceResponseModel
     */
    @WebMethod(operationName = "AddSoftInvoice", action = "/CustomerInfo/Service/v1/AccountServiceV1/AddSoftInvoice")
    @WebResult(name = "AddSoftInvoiceResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "AddSoftInvoice", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.AddSoftInvoice")
    @ResponseWrapper(localName = "AddSoftInvoiceResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.AddSoftInvoiceResponse")
    public AddSoftInvoiceResponseModel addSoftInvoice(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        AddSoftInvoiceRequestModel request);

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crmaccountcoa.RemoveSoftInvoiceResponseModel
     */
    @WebMethod(operationName = "RemoveSoftInvoice", action = "/CustomerInfo/Service/v1/AccountServiceV1/RemoveSoftInvoice")
    @WebResult(name = "RemoveSoftInvoiceResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "RemoveSoftInvoice", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.RemoveSoftInvoice")
    @ResponseWrapper(localName = "RemoveSoftInvoiceResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.RemoveSoftInvoiceResponse")
    public RemoveSoftInvoiceResponseModel removeSoftInvoice(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        RemoveSoftInvoiceRequestModel request);

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crmaccountcoa.ChangeAccountDealerResponseModel
     * @throws AccountServiceV1ChangeDealerBusinessFaultFaultFaultMessage
     * @throws AccountServiceV1ChangeDealerSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ChangeDealer", action = "/CustomerInfo/Service/v1/AccountServiceV1/ChangeDealer")
    @WebResult(name = "ChangeDealerResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "ChangeDealer", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.ChangeDealer")
    @ResponseWrapper(localName = "ChangeDealerResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.ChangeDealerResponse")
    public ChangeAccountDealerResponseModel changeDealer(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        ChangeAccountDealerRequestModel request)
        throws AccountServiceV1ChangeDealerBusinessFaultFaultFaultMessage, AccountServiceV1ChangeDealerSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crmaccountcoa.ProcessProcessRequestResponseModel
     * @throws AccountServiceV1AddDeactivationRequestThenProcessSystemFaultFaultFaultMessage
     * @throws AccountServiceV1AddDeactivationRequestThenProcessBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "AddDeactivationRequestThenProcess", action = "/CustomerInfo/Service/v1/AccountServiceV1/AddDeactivationRequestThenProcess")
    @WebResult(name = "AddDeactivationRequestThenProcessResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "AddDeactivationRequestThenProcess", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.AddDeactivationRequestThenProcess")
    @ResponseWrapper(localName = "AddDeactivationRequestThenProcessResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.AddDeactivationRequestThenProcessResponse")
    public ProcessProcessRequestResponseModel addDeactivationRequestThenProcess(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        AddDeactivationRequestToAccountRequestModel request)
        throws AccountServiceV1AddDeactivationRequestThenProcessBusinessFaultFaultFaultMessage, AccountServiceV1AddDeactivationRequestThenProcessSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crmaccountcoa.MakePrepaidTransactionResponseModel
     */
    @WebMethod(operationName = "MakePrepaidTransaction", action = "/CustomerInfo/Service/v1/AccountServiceV1/MakePrepaidTransaction")
    @WebResult(name = "MakePrepaidTransactionResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "MakePrepaidTransaction", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.MakePrepaidTransaction")
    @ResponseWrapper(localName = "MakePrepaidTransactionResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.MakePrepaidTransactionResponse")
    public MakePrepaidTransactionResponseModel makePrepaidTransaction(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        MakePrepaidTransactionRequestModel request);

}
