
package org.milleni.dunning.ws.client.crmaccountcoa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AccountServiceV1", targetNamespace = "/CustomerInfo/Service/v1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccountServiceV1 {


    /**
     * 
     * @param req
     * @return
     *     returns org.milleni.dunning.ws.client.crmaccountcoa.SendAnnounceByBillingCustomerNoResponseModel
     * @throws AccountServiceV1SendIhtarAnnounceByBillingCustomerIdBusinessFaultFaultFaultMessage
     * @throws AccountServiceV1SendIhtarAnnounceByBillingCustomerIdSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SendIhtarAnnounceByBillingCustomerId", action = "/CustomerInfo/Service/v1/AccountServiceV1/SendIhtarAnnounceByBillingCustomerId")
    @WebResult(name = "SendIhtarAnnounceByBillingCustomerIdResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "SendIhtarAnnounceByBillingCustomerId", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.SendIhtarAnnounceByBillingCustomerId")
    @ResponseWrapper(localName = "SendIhtarAnnounceByBillingCustomerIdResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmaccountcoa.SendIhtarAnnounceByBillingCustomerIdResponse")
    public SendAnnounceByBillingCustomerNoResponseModel sendIhtarAnnounceByBillingCustomerId(
        @WebParam(name = "req", targetNamespace = "/CustomerInfo/Service/v1")
        SendAnnounceByBillingCustomerNoRequestModel req)
        throws AccountServiceV1SendIhtarAnnounceByBillingCustomerIdBusinessFaultFaultFaultMessage, AccountServiceV1SendIhtarAnnounceByBillingCustomerIdSystemFaultFaultFaultMessage
    ;

}
