
package org.milleni.dunning.ws.client.customerstatus;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CustomerStatusOperations", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/", wsdlLocation = "http://localhost:43324/CustomerStatusOperations.asmx?WSDL")
public class CustomerStatusOperations
    extends Service
{

    private final static URL CUSTOMERSTATUSOPERATIONS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.milleni.dunning.ws.client.customerstatus.CustomerStatusOperations.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.milleni.dunning.ws.client.customerstatus.CustomerStatusOperations.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:43324/CustomerStatusOperations.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:43324/CustomerStatusOperations.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CUSTOMERSTATUSOPERATIONS_WSDL_LOCATION = url;
    }

    public CustomerStatusOperations(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerStatusOperations() {
        super(CUSTOMERSTATUSOPERATIONS_WSDL_LOCATION, new QName("http://milleni.com.tr/CustomerStatusOperations/", "CustomerStatusOperations"));
    }

    /**
     * 
     * @return
     *     returns CustomerStatusOperationsSoap
     */
    @WebEndpoint(name = "CustomerStatusOperationsSoap")
    public CustomerStatusOperationsSoap getCustomerStatusOperationsSoap() {
        return super.getPort(new QName("http://milleni.com.tr/CustomerStatusOperations/", "CustomerStatusOperationsSoap"), CustomerStatusOperationsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerStatusOperationsSoap
     */
    @WebEndpoint(name = "CustomerStatusOperationsSoap")
    public CustomerStatusOperationsSoap getCustomerStatusOperationsSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://milleni.com.tr/CustomerStatusOperations/", "CustomerStatusOperationsSoap"), CustomerStatusOperationsSoap.class, features);
    }

}
