
package org.milleni.dunning.ws.client.customerstatus;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CustomerStatusOperationsSoap", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerStatusOperationsSoap {


    /**
     * 
     * @param guid
     * @param customerId
     * @param reason
     * @param status
     * @return
     *     returns org.milleni.dunning.ws.client.customerstatus.ContractServiceResponse
     */
    @WebMethod(action = "http://milleni.com.tr/CustomerStatusOperations/changeCrmCustomerStatus")
    @WebResult(name = "changeCrmCustomerStatusResult", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/")
    @RequestWrapper(localName = "changeCrmCustomerStatus", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/", className = "org.milleni.dunning.ws.client.customerstatus.ChangeCrmCustomerStatus")
    @ResponseWrapper(localName = "changeCrmCustomerStatusResponse", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/", className = "org.milleni.dunning.ws.client.customerstatus.ChangeCrmCustomerStatusResponse")
    public ContractServiceResponse changeCrmCustomerStatus(
        @WebParam(name = "guid", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/")
        String guid,
        @WebParam(name = "customerId", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/")
        long customerId,
        @WebParam(name = "status", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/")
        STATUS status,
        @WebParam(name = "reason", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/")
        int reason);

    /**
     * 
     * @param guid
     * @param application
     * @param customerId
     * @param reason
     * @param status
     * @return
     *     returns org.milleni.dunning.ws.client.customerstatus.ServiceResponse
     */
    @WebMethod(action = "http://milleni.com.tr/CustomerStatusOperations/changeCustomerStatus")
    @WebResult(name = "changeCustomerStatusResult", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/")
    @RequestWrapper(localName = "changeCustomerStatus", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/", className = "org.milleni.dunning.ws.client.customerstatus.ChangeCustomerStatus")
    @ResponseWrapper(localName = "changeCustomerStatusResponse", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/", className = "org.milleni.dunning.ws.client.customerstatus.ChangeCustomerStatusResponse")
    public ServiceResponse changeCustomerStatus(
        @WebParam(name = "guid", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/")
        String guid,
        @WebParam(name = "customerId", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/")
        long customerId,
        @WebParam(name = "status", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/")
        STATUS status,
        @WebParam(name = "reason", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/")
        STATUSREASON reason,
        @WebParam(name = "application", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/")
        String application);

    /**
     * 
     * @param guid
     * @param customerId
     * @param status
     * @return
     *     returns org.milleni.dunning.ws.client.customerstatus.ContractServiceResponse
     */
    @WebMethod(action = "http://milleni.com.tr/CustomerStatusOperations/changeCustomerTTCRMStatus")
    @WebResult(name = "changeCustomerTTCRMStatusResult", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/")
    @RequestWrapper(localName = "changeCustomerTTCRMStatus", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/", className = "org.milleni.dunning.ws.client.customerstatus.ChangeCustomerTTCRMStatus")
    @ResponseWrapper(localName = "changeCustomerTTCRMStatusResponse", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/", className = "org.milleni.dunning.ws.client.customerstatus.ChangeCustomerTTCRMStatusResponse")
    public ContractServiceResponse changeCustomerTTCRMStatus(
        @WebParam(name = "guid", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/")
        String guid,
        @WebParam(name = "customerId", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/")
        long customerId,
        @WebParam(name = "status", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/")
        TTSTATUS status);

    /**
     * 
     * @param guid
     * @param customerId
     * @param status
     * @return
     *     returns org.milleni.dunning.ws.client.customerstatus.ServiceResponse
     */
    @WebMethod(action = "http://milleni.com.tr/CustomerStatusOperations/voipChangeCustomerStatus")
    @WebResult(name = "voipChangeCustomerStatusResult", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/")
    @RequestWrapper(localName = "voipChangeCustomerStatus", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/", className = "org.milleni.dunning.ws.client.customerstatus.VoipChangeCustomerStatus")
    @ResponseWrapper(localName = "voipChangeCustomerStatusResponse", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/", className = "org.milleni.dunning.ws.client.customerstatus.VoipChangeCustomerStatusResponse")
    public ServiceResponse voipChangeCustomerStatus(
        @WebParam(name = "guid", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/")
        String guid,
        @WebParam(name = "customerId", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/")
        long customerId,
        @WebParam(name = "status", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/")
        STATUS status);

    /**
     * 
     * @param guid
     * @param customerId
     * @return
     *     returns org.milleni.dunning.ws.client.customerstatus.ServiceResponse
     */
    @WebMethod(action = "http://milleni.com.tr/CustomerStatusOperations/oloThkAboneIptal")
    @WebResult(name = "oloThkAboneIptalResult", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/")
    @RequestWrapper(localName = "oloThkAboneIptal", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/", className = "org.milleni.dunning.ws.client.customerstatus.OloThkAboneIptal")
    @ResponseWrapper(localName = "oloThkAboneIptalResponse", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/", className = "org.milleni.dunning.ws.client.customerstatus.OloThkAboneIptalResponse")
    public ServiceResponse oloThkAboneIptal(
        @WebParam(name = "guid", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/")
        String guid,
        @WebParam(name = "customerId", targetNamespace = "http://milleni.com.tr/CustomerStatusOperations/")
        long customerId);

}
