
package org.milleni.dunning.ws.client.customerservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CustomerInfoService", targetNamespace = "http://milleni.com.tr/CustomerInfoService/", wsdlLocation = "http://192.168.2.18/MilleniWs/CustomerInfoService.asmx?WSDL")
public class CustomerInfoService
    extends Service
{

    private final static URL CUSTOMERINFOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.milleni.dunning.ws.client.customerservice.CustomerInfoService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.milleni.dunning.ws.client.customerservice.CustomerInfoService.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.2.18/MilleniWs/CustomerInfoService.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.2.18/MilleniWs/CustomerInfoService.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CUSTOMERINFOSERVICE_WSDL_LOCATION = url;
    }

    public CustomerInfoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerInfoService() {
        super(CUSTOMERINFOSERVICE_WSDL_LOCATION, new QName("http://milleni.com.tr/CustomerInfoService/", "CustomerInfoService"));
    }

    /**
     * 
     * @return
     *     returns CustomerInfoServiceSoap
     */
    @WebEndpoint(name = "CustomerInfoServiceSoap")
    public CustomerInfoServiceSoap getCustomerInfoServiceSoap() {
        return super.getPort(new QName("http://milleni.com.tr/CustomerInfoService/", "CustomerInfoServiceSoap"), CustomerInfoServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerInfoServiceSoap
     */
    @WebEndpoint(name = "CustomerInfoServiceSoap")
    public CustomerInfoServiceSoap getCustomerInfoServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://milleni.com.tr/CustomerInfoService/", "CustomerInfoServiceSoap"), CustomerInfoServiceSoap.class, features);
    }

}
