
package org.milleni.dunning.ws.client.customerservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CustomerInfoServiceSoap", targetNamespace = "http://milleni.com.tr/CustomerInfoService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerInfoServiceSoap {


    /**
     * 
     * @param guid
     * @param customerId
     * @param contractDetail
     * @return
     *     returns org.milleni.dunning.ws.client.customerservice.TeconCustomerInfoResponse
     */
    @WebMethod(action = "http://milleni.com.tr/CustomerInfoService/retrieveCustomerInfo")
    @WebResult(name = "retrieveCustomerInfoResult", targetNamespace = "http://milleni.com.tr/CustomerInfoService/")
    @RequestWrapper(localName = "retrieveCustomerInfo", targetNamespace = "http://milleni.com.tr/CustomerInfoService/", className = "org.milleni.dunning.ws.client.customerservice.RetrieveCustomerInfo")
    @ResponseWrapper(localName = "retrieveCustomerInfoResponse", targetNamespace = "http://milleni.com.tr/CustomerInfoService/", className = "org.milleni.dunning.ws.client.customerservice.RetrieveCustomerInfoResponse")
    public TeconCustomerInfoResponse retrieveCustomerInfo(
        @WebParam(name = "guid", targetNamespace = "http://milleni.com.tr/CustomerInfoService/")
        String guid,
        @WebParam(name = "customerId", targetNamespace = "http://milleni.com.tr/CustomerInfoService/")
        long customerId,
        @WebParam(name = "contractDetail", targetNamespace = "http://milleni.com.tr/CustomerInfoService/")
        boolean contractDetail);

    /**
     * 
     * @param guid
     * @param customerId
     * @return
     *     returns org.milleni.dunning.ws.client.customerservice.TeconCustomerInfoResponse
     */
    @WebMethod(action = "http://milleni.com.tr/CustomerInfoService/retrieveCustomerStatus")
    @WebResult(name = "retrieveCustomerStatusResult", targetNamespace = "http://milleni.com.tr/CustomerInfoService/")
    @RequestWrapper(localName = "retrieveCustomerStatus", targetNamespace = "http://milleni.com.tr/CustomerInfoService/", className = "org.milleni.dunning.ws.client.customerservice.RetrieveCustomerStatus")
    @ResponseWrapper(localName = "retrieveCustomerStatusResponse", targetNamespace = "http://milleni.com.tr/CustomerInfoService/", className = "org.milleni.dunning.ws.client.customerservice.RetrieveCustomerStatusResponse")
    public TeconCustomerInfoResponse retrieveCustomerStatus(
        @WebParam(name = "guid", targetNamespace = "http://milleni.com.tr/CustomerInfoService/")
        String guid,
        @WebParam(name = "customerId", targetNamespace = "http://milleni.com.tr/CustomerInfoService/")
        long customerId);

    /**
     * 
     * @param guid
     * @param customerId
     * @return
     *     returns int
     */
    @WebMethod(action = "http://milleni.com.tr/CustomerInfoService/retrieveCustomerTaksitCount")
    @WebResult(name = "retrieveCustomerTaksitCountResult", targetNamespace = "http://milleni.com.tr/CustomerInfoService/")
    @RequestWrapper(localName = "retrieveCustomerTaksitCount", targetNamespace = "http://milleni.com.tr/CustomerInfoService/", className = "org.milleni.dunning.ws.client.customerservice.RetrieveCustomerTaksitCount")
    @ResponseWrapper(localName = "retrieveCustomerTaksitCountResponse", targetNamespace = "http://milleni.com.tr/CustomerInfoService/", className = "org.milleni.dunning.ws.client.customerservice.RetrieveCustomerTaksitCountResponse")
    public int retrieveCustomerTaksitCount(
        @WebParam(name = "guid", targetNamespace = "http://milleni.com.tr/CustomerInfoService/")
        String guid,
        @WebParam(name = "customerId", targetNamespace = "http://milleni.com.tr/CustomerInfoService/")
        long customerId);

    /**
     * 
     * @param guid
     * @param customerId
     * @return
     *     returns int
     */
    @WebMethod(action = "http://milleni.com.tr/CustomerInfoService/retrieveCustomerAgreementDocumentCount")
    @WebResult(name = "retrieveCustomerAgreementDocumentCountResult", targetNamespace = "http://milleni.com.tr/CustomerInfoService/")
    @RequestWrapper(localName = "retrieveCustomerAgreementDocumentCount", targetNamespace = "http://milleni.com.tr/CustomerInfoService/", className = "org.milleni.dunning.ws.client.customerservice.RetrieveCustomerAgreementDocumentCount")
    @ResponseWrapper(localName = "retrieveCustomerAgreementDocumentCountResponse", targetNamespace = "http://milleni.com.tr/CustomerInfoService/", className = "org.milleni.dunning.ws.client.customerservice.RetrieveCustomerAgreementDocumentCountResponse")
    public int retrieveCustomerAgreementDocumentCount(
        @WebParam(name = "guid", targetNamespace = "http://milleni.com.tr/CustomerInfoService/")
        String guid,
        @WebParam(name = "customerId", targetNamespace = "http://milleni.com.tr/CustomerInfoService/")
        long customerId);

    /**
     * 
     * @param guid
     * @param customerId
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://milleni.com.tr/CustomerInfoService/retrieveCustomerCdr")
    @WebResult(name = "retrieveCustomerCdrResult", targetNamespace = "http://milleni.com.tr/CustomerInfoService/")
    @RequestWrapper(localName = "retrieveCustomerCdr", targetNamespace = "http://milleni.com.tr/CustomerInfoService/", className = "org.milleni.dunning.ws.client.customerservice.RetrieveCustomerCdr")
    @ResponseWrapper(localName = "retrieveCustomerCdrResponse", targetNamespace = "http://milleni.com.tr/CustomerInfoService/", className = "org.milleni.dunning.ws.client.customerservice.RetrieveCustomerCdrResponse")
    public boolean retrieveCustomerCdr(
        @WebParam(name = "guid", targetNamespace = "http://milleni.com.tr/CustomerInfoService/")
        String guid,
        @WebParam(name = "customerId", targetNamespace = "http://milleni.com.tr/CustomerInfoService/")
        long customerId);

    /**
     * Mobil Numaradan Aylik kullanim bilgisini getirir.  
     * 
     * @param mobil
     * @return
     *     returns org.milleni.dunning.ws.client.customerservice.UsageResponse
     */
    @WebMethod(operationName = "GetUsage", action = "http://milleni.com.tr/CustomerInfoService/GetUsage")
    @WebResult(name = "GetUsageResult", targetNamespace = "http://milleni.com.tr/CustomerInfoService/")
    @RequestWrapper(localName = "GetUsage", targetNamespace = "http://milleni.com.tr/CustomerInfoService/", className = "org.milleni.dunning.ws.client.customerservice.GetUsage")
    @ResponseWrapper(localName = "GetUsageResponse", targetNamespace = "http://milleni.com.tr/CustomerInfoService/", className = "org.milleni.dunning.ws.client.customerservice.GetUsageResponse")
    public UsageResponse getUsage(
        @WebParam(name = "mobil", targetNamespace = "http://milleni.com.tr/CustomerInfoService/")
        String mobil);

}
