
package org.milleni.dunning.ws.client.milinternal;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MillenicomInternal", targetNamespace = "http://milleni.com/internal", wsdlLocation = "http://192.168.2.52/SAPWebServicesProd/MillenicomInternal.asmx?wsdl")
public class MillenicomInternal
    extends Service
{

    private final static URL MILLENICOMINTERNAL_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.milleni.dunning.ws.client.milinternal.MillenicomInternal.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.milleni.dunning.ws.client.milinternal.MillenicomInternal.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.2.52/SAPWebServicesProd/MillenicomInternal.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.2.52/SAPWebServicesProd/MillenicomInternal.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MILLENICOMINTERNAL_WSDL_LOCATION = url;
    }

    public MillenicomInternal(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MillenicomInternal() {
        super(MILLENICOMINTERNAL_WSDL_LOCATION, new QName("http://milleni.com/internal", "MillenicomInternal"));
    }

    /**
     * 
     * @return
     *     returns MillenicomInternalSoap
     */
    @WebEndpoint(name = "MillenicomInternalSoap")
    public MillenicomInternalSoap getMillenicomInternalSoap() {
        return super.getPort(new QName("http://milleni.com/internal", "MillenicomInternalSoap"), MillenicomInternalSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MillenicomInternalSoap
     */
    @WebEndpoint(name = "MillenicomInternalSoap")
    public MillenicomInternalSoap getMillenicomInternalSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://milleni.com/internal", "MillenicomInternalSoap"), MillenicomInternalSoap.class, features);
    }

}
