
package org.milleni.dunning.ws.client.milinternal;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MillenicomInternalSoap", targetNamespace = "http://milleni.com/internal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MillenicomInternalSoap {


    /**
     * Web service'in ve arkas\u0131ndaki R/3'ün eri\u015filebilir oldu\u011funu test etmek için kullan\u0131l\u0131r.
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Test", action = "http://milleni.com/internal/Test")
    @WebResult(name = "TestResult", targetNamespace = "http://milleni.com/internal")
    @RequestWrapper(localName = "Test", targetNamespace = "http://milleni.com/internal", className = "org.milleni.dunning.ws.client.milinternal.Test")
    @ResponseWrapper(localName = "TestResponse", targetNamespace = "http://milleni.com/internal", className = "org.milleni.dunning.ws.client.milinternal.TestResponse")
    public String test();

    /**
     * Belirli bir zaman aral\u0131\u011f\u0131nda (webpos ve banka tahsilatlar\u0131yla) suspendden aktife geçmi\u015f mü\u015fterileri sorgular
     * 
     * @param guvenlikBilgisi
     * @param sorgulamaBitisZamani
     * @param sorgulamaBaslangicZamani
     * @return
     *     returns org.milleni.dunning.ws.client.milinternal.ArrayOfMusteri
     */
    @WebMethod(operationName = "SuspenddenAktifeGecmisMusteriler", action = "http://milleni.com/internal/SuspenddenAktifeGecmisMusteriler")
    @WebResult(name = "SuspenddenAktifeGecmisMusterilerResult", targetNamespace = "http://milleni.com/internal")
    @RequestWrapper(localName = "SuspenddenAktifeGecmisMusteriler", targetNamespace = "http://milleni.com/internal", className = "org.milleni.dunning.ws.client.milinternal.SuspenddenAktifeGecmisMusteriler")
    @ResponseWrapper(localName = "SuspenddenAktifeGecmisMusterilerResponse", targetNamespace = "http://milleni.com/internal", className = "org.milleni.dunning.ws.client.milinternal.SuspenddenAktifeGecmisMusterilerResponse")
    public ArrayOfMusteri suspenddenAktifeGecmisMusteriler(
        @WebParam(name = "guvenlikBilgisi", targetNamespace = "http://milleni.com/internal")
        GuvenlikBilgisi guvenlikBilgisi,
        @WebParam(name = "sorgulamaBaslangicZamani", targetNamespace = "http://milleni.com/internal")
        String sorgulamaBaslangicZamani,
        @WebParam(name = "sorgulamaBitisZamani", targetNamespace = "http://milleni.com/internal")
        String sorgulamaBitisZamani);

    /**
     * Belirli bir zaman aral\u0131\u011f\u0131nda (manuel tahsilatlarla) suspendden aktife geçmi\u015f mü\u015fterileri sorgular
     * 
     * @param guvenlikBilgisi
     * @param sorgulamaBitisZamani
     * @param sorgulamaBaslangicZamani
     * @return
     *     returns org.milleni.dunning.ws.client.milinternal.ArrayOfMusteri
     */
    @WebMethod(operationName = "SuspenddenAktifeGecmisMusterilerManuelTahsilat", action = "http://milleni.com/internal/SuspenddenAktifeGecmisMusterilerManuelTahsilat")
    @WebResult(name = "SuspenddenAktifeGecmisMusterilerManuelTahsilatResult", targetNamespace = "http://milleni.com/internal")
    @RequestWrapper(localName = "SuspenddenAktifeGecmisMusterilerManuelTahsilat", targetNamespace = "http://milleni.com/internal", className = "org.milleni.dunning.ws.client.milinternal.SuspenddenAktifeGecmisMusterilerManuelTahsilat")
    @ResponseWrapper(localName = "SuspenddenAktifeGecmisMusterilerManuelTahsilatResponse", targetNamespace = "http://milleni.com/internal", className = "org.milleni.dunning.ws.client.milinternal.SuspenddenAktifeGecmisMusterilerManuelTahsilatResponse")
    public ArrayOfMusteri suspenddenAktifeGecmisMusterilerManuelTahsilat(
        @WebParam(name = "guvenlikBilgisi", targetNamespace = "http://milleni.com/internal")
        GuvenlikBilgisi guvenlikBilgisi,
        @WebParam(name = "sorgulamaBaslangicZamani", targetNamespace = "http://milleni.com/internal")
        String sorgulamaBaslangicZamani,
        @WebParam(name = "sorgulamaBitisZamani", targetNamespace = "http://milleni.com/internal")
        String sorgulamaBitisZamani);

    /**
     * SAP'de mü\u015fterilerin durumlar\u0131n\u0131 günceller
     * 
     * @param guvenlikBilgisi
     * @param musteriDurumlari
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MusteriDurumlariniGuncelle", action = "http://milleni.com/internal/MusteriDurumlariniGuncelle")
    @WebResult(name = "MusteriDurumlariniGuncelleResult", targetNamespace = "http://milleni.com/internal")
    @RequestWrapper(localName = "MusteriDurumlariniGuncelle", targetNamespace = "http://milleni.com/internal", className = "org.milleni.dunning.ws.client.milinternal.MusteriDurumlariniGuncelle")
    @ResponseWrapper(localName = "MusteriDurumlariniGuncelleResponse", targetNamespace = "http://milleni.com/internal", className = "org.milleni.dunning.ws.client.milinternal.MusteriDurumlariniGuncelleResponse")
    public String musteriDurumlariniGuncelle(
        @WebParam(name = "guvenlikBilgisi", targetNamespace = "http://milleni.com/internal")
        GuvenlikBilgisi guvenlikBilgisi,
        @WebParam(name = "musteriDurumlari", targetNamespace = "http://milleni.com/internal")
        ArrayOfMusteriDurumu musteriDurumlari);

    /**
     * SAP'de mü\u015fterinin girilen tarihe kadar olan fatura detaylar\u0131n\u0131 görüntüler
     * 
     * @param guvenlikBilgisi
     * @param musteriNumarasi
     * @param sorgumaZamani
     * @return
     *     returns org.milleni.dunning.ws.client.milinternal.FaturaDetayi
     */
    @WebMethod(operationName = "FaturaDetayiGoruntule", action = "http://milleni.com/internal/FaturaDetayiGoruntule")
    @WebResult(name = "FaturaDetayiGoruntuleResult", targetNamespace = "http://milleni.com/internal")
    @RequestWrapper(localName = "FaturaDetayiGoruntule", targetNamespace = "http://milleni.com/internal", className = "org.milleni.dunning.ws.client.milinternal.FaturaDetayiGoruntule")
    @ResponseWrapper(localName = "FaturaDetayiGoruntuleResponse", targetNamespace = "http://milleni.com/internal", className = "org.milleni.dunning.ws.client.milinternal.FaturaDetayiGoruntuleResponse")
    public FaturaDetayi faturaDetayiGoruntule(
        @WebParam(name = "guvenlikBilgisi", targetNamespace = "http://milleni.com/internal")
        GuvenlikBilgisi guvenlikBilgisi,
        @WebParam(name = "musteriNumarasi", targetNamespace = "http://milleni.com/internal")
        String musteriNumarasi,
        @WebParam(name = "sorgumaZamani", targetNamespace = "http://milleni.com/internal")
        String sorgumaZamani);

}
