
package org.milleni.dunning.ws.client.coa;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "COA", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://192.168.2.18/MilleniWS/coa.asmx?WSDL")
public class COA
    extends Service
{

    private final static URL COA_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.milleni.dunning.ws.client.coa.COA.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.milleni.dunning.ws.client.coa.COA.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.2.18/MilleniWS/coa.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.2.18/MilleniWS/coa.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        COA_WSDL_LOCATION = url;
    }

    public COA(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public COA() {
        super(COA_WSDL_LOCATION, new QName("http://tempuri.org/", "COA"));
    }

    /**
     * 
     * @return
     *     returns COASoap
     */
    @WebEndpoint(name = "COASoap")
    public COASoap getCOASoap() {
        return super.getPort(new QName("http://tempuri.org/", "COASoap"), COASoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns COASoap
     */
    @WebEndpoint(name = "COASoap")
    public COASoap getCOASoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "COASoap"), COASoap.class, features);
    }

}
