
package org.milleni.dunning.ws.client.coa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "COASoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface COASoap {


    /**
     * 
     * @param loginName
     * @return
     *     returns org.milleni.dunning.ws.client.coa.CustomerResponse
     */
    @WebMethod(operationName = "GetCustomerFromLoginName", action = "http://tempuri.org/GetCustomerFromLoginName")
    @WebResult(name = "GetCustomerFromLoginNameResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCustomerFromLoginName", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.coa.GetCustomerFromLoginName")
    @ResponseWrapper(localName = "GetCustomerFromLoginNameResponse", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.coa.GetCustomerFromLoginNameResponse")
    public CustomerResponse getCustomerFromLoginName(
        @WebParam(name = "loginName", targetNamespace = "http://tempuri.org/")
        String loginName);

    /**
     * 
     * @param loginName
     * @return
     *     returns org.milleni.dunning.ws.client.coa.CustomerResponse
     */
    @WebMethod(operationName = "GetCustomerAndQuotaFromLoginName", action = "http://tempuri.org/GetCustomerAndQuotaFromLoginName")
    @WebResult(name = "GetCustomerAndQuotaFromLoginNameResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCustomerAndQuotaFromLoginName", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.coa.GetCustomerAndQuotaFromLoginName")
    @ResponseWrapper(localName = "GetCustomerAndQuotaFromLoginNameResponse", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.coa.GetCustomerAndQuotaFromLoginNameResponse")
    public CustomerResponse getCustomerAndQuotaFromLoginName(
        @WebParam(name = "loginName", targetNamespace = "http://tempuri.org/")
        String loginName);

    /**
     * 
     * @param customerID
     * @param loginName
     * @return
     *     returns org.milleni.dunning.ws.client.coa.COAUpdateResponse
     */
    @WebMethod(operationName = "IsCustomerUpdateBefore", action = "http://tempuri.org/IsCustomerUpdateBefore")
    @WebResult(name = "IsCustomerUpdateBeforeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IsCustomerUpdateBefore", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.coa.IsCustomerUpdateBefore")
    @ResponseWrapper(localName = "IsCustomerUpdateBeforeResponse", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.coa.IsCustomerUpdateBeforeResponse")
    public COAUpdateResponse isCustomerUpdateBefore(
        @WebParam(name = "customerID", targetNamespace = "http://tempuri.org/")
        int customerID,
        @WebParam(name = "loginName", targetNamespace = "http://tempuri.org/")
        String loginName);

    /**
     * 
     * @param invoiceMail
     * @param email
     * @param mobil
     * @param updateIp
     * @param customerID
     * @param loginName
     * @return
     *     returns org.milleni.dunning.ws.client.coa.ServiceResponse
     */
    @WebMethod(operationName = "UpdateUserInfo", action = "http://tempuri.org/UpdateUserInfo")
    @WebResult(name = "UpdateUserInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateUserInfo", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.coa.UpdateUserInfo")
    @ResponseWrapper(localName = "UpdateUserInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.coa.UpdateUserInfoResponse")
    public ServiceResponse updateUserInfo(
        @WebParam(name = "customerID", targetNamespace = "http://tempuri.org/")
        int customerID,
        @WebParam(name = "loginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "email", targetNamespace = "http://tempuri.org/")
        String email,
        @WebParam(name = "mobil", targetNamespace = "http://tempuri.org/")
        String mobil,
        @WebParam(name = "updateIp", targetNamespace = "http://tempuri.org/")
        String updateIp,
        @WebParam(name = "invoiceMail", targetNamespace = "http://tempuri.org/")
        boolean invoiceMail);

    /**
     * Mü\u015fterinin tüm kontratlar\u0131na COA Basar.
     * 
     * @param customerId
     * @param batchProcess
     * @param channelId
     * @param announceType
     * @return
     *     returns org.milleni.dunning.ws.client.coa.ServiceResponse
     */
    @WebMethod(operationName = "SendAnnounceCoa", action = "http://tempuri.org/SendAnnounceCoa")
    @WebResult(name = "SendAnnounceCoaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendAnnounceCoa", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.coa.SendAnnounceCoa")
    @ResponseWrapper(localName = "SendAnnounceCoaResponse", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.coa.SendAnnounceCoaResponse")
    public ServiceResponse sendAnnounceCoa(
        @WebParam(name = "channelId", targetNamespace = "http://tempuri.org/")
        int channelId,
        @WebParam(name = "customerId", targetNamespace = "http://tempuri.org/")
        int customerId,
        @WebParam(name = "announceType", targetNamespace = "http://tempuri.org/")
        int announceType,
        @WebParam(name = "batchProcess", targetNamespace = "http://tempuri.org/")
        boolean batchProcess);

    /**
     * Mü\u015fterinin belli bir kontrat\u0131na COA Basar.
     * 
     * @param customerId
     * @param batchProcess
     * @param channelId
     * @param contractId
     * @param announceType
     * @return
     *     returns org.milleni.dunning.ws.client.coa.ServiceResponse
     */
    @WebMethod(operationName = "SendAnnounceContract", action = "http://tempuri.org/SendAnnounceContract")
    @WebResult(name = "SendAnnounceContractResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendAnnounceContract", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.coa.SendAnnounceContract")
    @ResponseWrapper(localName = "SendAnnounceContractResponse", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.coa.SendAnnounceContractResponse")
    public ServiceResponse sendAnnounceContract(
        @WebParam(name = "channelId", targetNamespace = "http://tempuri.org/")
        int channelId,
        @WebParam(name = "announceType", targetNamespace = "http://tempuri.org/")
        int announceType,
        @WebParam(name = "customerId", targetNamespace = "http://tempuri.org/")
        int customerId,
        @WebParam(name = "contractId", targetNamespace = "http://tempuri.org/")
        int contractId,
        @WebParam(name = "batchProcess", targetNamespace = "http://tempuri.org/")
        boolean batchProcess);

    /**
     * NET Fatura Kota A\u015f\u0131m\u0131nda Hizmete Devam Etme iste\u011fi Gönderir
     * 
     * @param contractID
     * @param loginName
     * @return
     *     returns org.milleni.dunning.ws.client.coa.ServiceResponse
     */
    @WebMethod(operationName = "NetFaturaResumeRequest", action = "http://tempuri.org/NetFaturaResumeRequest")
    @WebResult(name = "NetFaturaResumeRequestResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "NetFaturaResumeRequest", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.coa.NetFaturaResumeRequest")
    @ResponseWrapper(localName = "NetFaturaResumeRequestResponse", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.coa.NetFaturaResumeRequestResponse")
    public ServiceResponse netFaturaResumeRequest(
        @WebParam(name = "contractID", targetNamespace = "http://tempuri.org/")
        long contractID,
        @WebParam(name = "loginName", targetNamespace = "http://tempuri.org/")
        String loginName);

    /**
     * Taahhüt Uzatma Teklif Sonucunu Al\u0131r
     * 
     * @param offerType
     * @param customerId
     * @param preAppealId
     * @param updateIp
     * @param loginName
     * @return
     *     returns org.milleni.dunning.ws.client.coa.ServiceResponse
     */
    @WebMethod(operationName = "OfferCommitmentResumeRequest", action = "http://tempuri.org/OfferCommitmentResumeRequest")
    @WebResult(name = "OfferCommitmentResumeRequestResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "OfferCommitmentResumeRequest", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.coa.OfferCommitmentResumeRequest")
    @ResponseWrapper(localName = "OfferCommitmentResumeRequestResponse", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.coa.OfferCommitmentResumeRequestResponse")
    public ServiceResponse offerCommitmentResumeRequest(
        @WebParam(name = "customerId", targetNamespace = "http://tempuri.org/")
        int customerId,
        @WebParam(name = "loginName", targetNamespace = "http://tempuri.org/")
        String loginName,
        @WebParam(name = "updateIp", targetNamespace = "http://tempuri.org/")
        String updateIp,
        @WebParam(name = "offerType", targetNamespace = "http://tempuri.org/")
        int offerType,
        @WebParam(name = "preAppealId", targetNamespace = "http://tempuri.org/")
        int preAppealId);

    /**
     * Mü\u015fterinin belli bir kontrat\u0131n\u0131n Coa iptalini gerçekle\u015ftirir.
     * 
     * @param customerId
     * @param channelId
     * @param contractId
     * @param announceType
     * @return
     *     returns org.milleni.dunning.ws.client.coa.ServiceResponse
     */
    @WebMethod(operationName = "CancelAnnouceContract", action = "http://tempuri.org/CancelAnnouceContract")
    @WebResult(name = "CancelAnnouceContractResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelAnnouceContract", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.coa.CancelAnnouceContract")
    @ResponseWrapper(localName = "CancelAnnouceContractResponse", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.coa.CancelAnnouceContractResponse")
    public ServiceResponse cancelAnnouceContract(
        @WebParam(name = "channelId", targetNamespace = "http://tempuri.org/")
        int channelId,
        @WebParam(name = "announceType", targetNamespace = "http://tempuri.org/")
        int announceType,
        @WebParam(name = "customerId", targetNamespace = "http://tempuri.org/")
        int customerId,
        @WebParam(name = "contractId", targetNamespace = "http://tempuri.org/")
        int contractId);

}
