
package org.milleni.dunning.ws.client.crmcontact;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ContatServiceV1", targetNamespace = "/CustomerInfo/Service/v1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ContatServiceV1 {


    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crmcontact.UpdateContactResponseModel
     * @throws ContatServiceV1UpdateContactInfoBusinessFaultFaultFaultMessage
     * @throws ContatServiceV1UpdateContactInfoSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateContactInfo", action = "/CustomerInfo/Service/v1/ContatServiceV1/UpdateContactInfo")
    @WebResult(name = "UpdateContactInfoResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "UpdateContactInfo", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmcontact.UpdateContactInfo")
    @ResponseWrapper(localName = "UpdateContactInfoResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmcontact.UpdateContactInfoResponse")
    public UpdateContactResponseModel updateContactInfo(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        UpdateContactRequestModel request)
        throws ContatServiceV1UpdateContactInfoBusinessFaultFaultFaultMessage, ContatServiceV1UpdateContactInfoSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crmcontact.SendSmsByBillingCustomerNoResponseModel
     * @throws ContatServiceV1SendSmsByBillingCustomerNoBusinessFaultFaultFaultMessage
     * @throws ContatServiceV1SendSmsByBillingCustomerNoSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SendSmsByBillingCustomerNo", action = "/CustomerInfo/Service/v1/ContatServiceV1/SendSmsByBillingCustomerNo")
    @WebResult(name = "SendSmsByBillingCustomerNoResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "SendSmsByBillingCustomerNo", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmcontact.SendSmsByBillingCustomerNo")
    @ResponseWrapper(localName = "SendSmsByBillingCustomerNoResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmcontact.SendSmsByBillingCustomerNoResponse")
    public SendSmsByBillingCustomerNoResponseModel sendSmsByBillingCustomerNo(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        SendSmsByBillingCustomerNoRequestModel request)
        throws ContatServiceV1SendSmsByBillingCustomerNoBusinessFaultFaultFaultMessage, ContatServiceV1SendSmsByBillingCustomerNoSystemFaultFaultFaultMessage
    ;

}
