
package org.milleni.dunning.ws.client.crmcontact;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ContactServiceV1", targetNamespace = "/CustomerInfo/Service/v1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ContactServiceV1 {


    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crmcontact.UpdateContactResponseModel
     * @throws ContactServiceV1UpdateContactInfoSystemFaultFaultFaultMessage
     * @throws ContactServiceV1UpdateContactInfoBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateContactInfo", action = "/CustomerInfo/Service/v1/ContactServiceV1/UpdateContactInfo")
    @WebResult(name = "UpdateContactInfoResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "UpdateContactInfo", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmcontact.UpdateContactInfo")
    @ResponseWrapper(localName = "UpdateContactInfoResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmcontact.UpdateContactInfoResponse")
    public UpdateContactResponseModel updateContactInfo(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        UpdateContactRequestModel request)
        throws ContactServiceV1UpdateContactInfoBusinessFaultFaultFaultMessage, ContactServiceV1UpdateContactInfoSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.crmcontact.SendSmsByBillingCustomerNoResponseModel
     * @throws ContactServiceV1SendSmsByBillingCustomerNoSystemFaultFaultFaultMessage
     * @throws ContactServiceV1SendSmsByBillingCustomerNoBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SendSmsByBillingCustomerNo", action = "/CustomerInfo/Service/v1/ContactServiceV1/SendSmsByBillingCustomerNo")
    @WebResult(name = "SendSmsByBillingCustomerNoResult", targetNamespace = "/CustomerInfo/Service/v1")
    @RequestWrapper(localName = "SendSmsByBillingCustomerNo", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmcontact.SendSmsByBillingCustomerNo")
    @ResponseWrapper(localName = "SendSmsByBillingCustomerNoResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmcontact.SendSmsByBillingCustomerNoResponse")
    public SendSmsByBillingCustomerNoResponseModel sendSmsByBillingCustomerNo(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        SendSmsByBillingCustomerNoRequestModel request)
        throws ContactServiceV1SendSmsByBillingCustomerNoBusinessFaultFaultFaultMessage, ContactServiceV1SendSmsByBillingCustomerNoSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @throws ContactServiceV1SendDunningSmsBusinessFaultFaultFaultMessage
     * @throws ContactServiceV1SendDunningSmsSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SendDunningSms", action = "/CustomerInfo/Service/v1/ContactServiceV1/SendDunningSms")
    @RequestWrapper(localName = "SendDunningSms", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmcontact.SendDunningSms")
    @ResponseWrapper(localName = "SendDunningSmsResponse", targetNamespace = "/CustomerInfo/Service/v1", className = "org.milleni.dunning.ws.client.crmcontact.SendDunningSmsResponse")
    public void sendDunningSms(
        @WebParam(name = "request", targetNamespace = "/CustomerInfo/Service/v1")
        SendDunningSmsRequestModel request)
        throws ContactServiceV1SendDunningSmsBusinessFaultFaultFaultMessage, ContactServiceV1SendDunningSmsSystemFaultFaultFaultMessage
    ;

}
