
package org.milleni.dunning.ws.client.sms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "smsgwSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SmsgwSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Version", action = "http://tempuri.org/Version")
    @WebResult(name = "VersionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Version", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.sms.Version")
    @ResponseWrapper(localName = "VersionResponse", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.sms.VersionResponse")
    public String version();

    /**
     * 
     * @param message
     * @param application
     * @param numbers
     * @param userid
     * @param originator
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendSMS", action = "http://tempuri.org/SendSMS")
    @WebResult(name = "SendSMSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendSMS", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.sms.SendSMS")
    @ResponseWrapper(localName = "SendSMSResponse", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.sms.SendSMSResponse")
    public String sendSMS(
        @WebParam(name = "application", targetNamespace = "http://tempuri.org/")
        String application,
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        int userid,
        @WebParam(name = "originator", targetNamespace = "http://tempuri.org/")
        String originator,
        @WebParam(name = "numbers", targetNamespace = "http://tempuri.org/")
        String numbers,
        @WebParam(name = "message", targetNamespace = "http://tempuri.org/")
        String message);

}
