
package org.milleni.dunning.ws.client.freezexdsl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "FreezeDunningService", targetNamespace = "/FreezeDunning/Service/v1", wsdlLocation = "http://localhost:7636/FreezeDunningService.svc?singleWsdl")
public class FreezeDunningService
    extends Service
{

    private final static URL FREEZEDUNNINGSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.milleni.dunning.ws.client.freezexdsl.FreezeDunningService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.milleni.dunning.ws.client.freezexdsl.FreezeDunningService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:7636/FreezeDunningService.svc?singleWsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:7636/FreezeDunningService.svc?singleWsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        FREEZEDUNNINGSERVICE_WSDL_LOCATION = url;
    }

    public FreezeDunningService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FreezeDunningService() {
        super(FREEZEDUNNINGSERVICE_WSDL_LOCATION, new QName("/FreezeDunning/Service/v1", "FreezeDunningService"));
    }

    /**
     * 
     * @return
     *     returns IFreezeDunningService
     */
    @WebEndpoint(name = "BasicHttpBinding_IFreezeDunningService")
    public IFreezeDunningService getBasicHttpBindingIFreezeDunningService() {
        return super.getPort(new QName("/FreezeDunning/Service/v1", "BasicHttpBinding_IFreezeDunningService"), IFreezeDunningService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IFreezeDunningService
     */
    @WebEndpoint(name = "BasicHttpBinding_IFreezeDunningService")
    public IFreezeDunningService getBasicHttpBindingIFreezeDunningService(WebServiceFeature... features) {
        return super.getPort(new QName("/FreezeDunning/Service/v1", "BasicHttpBinding_IFreezeDunningService"), IFreezeDunningService.class, features);
    }

}
