
package org.milleni.dunning.ws.client.tts;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ITTSServiceV1", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ITTSServiceV1 {


    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.tts.GetActiveCallCentersResponseModel
     * @throws ITTSServiceV1GetActiveCallCentersBusinessFaultFaultFaultMessage
     * @throws ITTSServiceV1GetActiveCallCentersSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetActiveCallCenters", action = "http://tempuri.org/ITTSServiceV1/GetActiveCallCenters")
    @WebResult(name = "GetActiveCallCentersResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetActiveCallCenters", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.tts.GetActiveCallCenters")
    @ResponseWrapper(localName = "GetActiveCallCentersResponse", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.tts.GetActiveCallCentersResponse")
    public GetActiveCallCentersResponseModel getActiveCallCenters(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        GetActiveCallCentersRequestModel request)
        throws ITTSServiceV1GetActiveCallCentersBusinessFaultFaultFaultMessage, ITTSServiceV1GetActiveCallCentersSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.tts.GetActivePersonGroupsResponseModel
     * @throws ITTSServiceV1GetActivePersonGroupsBusinessFaultFaultFaultMessage
     * @throws ITTSServiceV1GetActivePersonGroupsSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetActivePersonGroups", action = "http://tempuri.org/ITTSServiceV1/GetActivePersonGroups")
    @WebResult(name = "GetActivePersonGroupsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetActivePersonGroups", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.tts.GetActivePersonGroups")
    @ResponseWrapper(localName = "GetActivePersonGroupsResponse", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.tts.GetActivePersonGroupsResponse")
    public GetActivePersonGroupsResponseModel getActivePersonGroups(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        GetActivePersonGroupsRequestModel request)
        throws ITTSServiceV1GetActivePersonGroupsBusinessFaultFaultFaultMessage, ITTSServiceV1GetActivePersonGroupsSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.tts.GetActivePersonResponseModel
     * @throws ITTSServiceV1GetActivePersonSystemFaultFaultFaultMessage
     * @throws ITTSServiceV1GetActivePersonBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetActivePerson", action = "http://tempuri.org/ITTSServiceV1/GetActivePerson")
    @WebResult(name = "GetActivePersonResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetActivePerson", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.tts.GetActivePerson")
    @ResponseWrapper(localName = "GetActivePersonResponse", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.tts.GetActivePersonResponse")
    public GetActivePersonResponseModel getActivePerson(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        GetActivePersonRequestModel request)
        throws ITTSServiceV1GetActivePersonBusinessFaultFaultFaultMessage, ITTSServiceV1GetActivePersonSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.tts.CreatePersonResponseModel
     * @throws ITTSServiceV1CreatePersonBusinessFaultFaultFaultMessage
     * @throws ITTSServiceV1CreatePersonSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "CreatePerson", action = "http://tempuri.org/ITTSServiceV1/CreatePerson")
    @WebResult(name = "CreatePersonResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreatePerson", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.tts.CreatePerson")
    @ResponseWrapper(localName = "CreatePersonResponse", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.tts.CreatePersonResponse")
    public CreatePersonResponseModel createPerson(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        CreatePersonRequestModel request)
        throws ITTSServiceV1CreatePersonBusinessFaultFaultFaultMessage, ITTSServiceV1CreatePersonSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.tts.DeactivatePersonResponseModel
     * @throws ITTSServiceV1DeactivatePersonSystemFaultFaultFaultMessage
     * @throws ITTSServiceV1DeactivatePersonBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "DeactivatePerson", action = "http://tempuri.org/ITTSServiceV1/DeactivatePerson")
    @WebResult(name = "DeactivatePersonResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DeactivatePerson", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.tts.DeactivatePerson")
    @ResponseWrapper(localName = "DeactivatePersonResponse", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.tts.DeactivatePersonResponse")
    public DeactivatePersonResponseModel deactivatePerson(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        DeactivatePersonRequestModel request)
        throws ITTSServiceV1DeactivatePersonBusinessFaultFaultFaultMessage, ITTSServiceV1DeactivatePersonSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.tts.UpdatePersonResponseModel
     * @throws ITTSServiceV1UpdatePersonBusinessFaultFaultFaultMessage
     * @throws ITTSServiceV1UpdatePersonSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UpdatePerson", action = "http://tempuri.org/ITTSServiceV1/UpdatePerson")
    @WebResult(name = "UpdatePersonResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdatePerson", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.tts.UpdatePerson")
    @ResponseWrapper(localName = "UpdatePersonResponse", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.tts.UpdatePersonResponse")
    public UpdatePersonResponseModel updatePerson(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        UpdatePersonRequestModel request)
        throws ITTSServiceV1UpdatePersonBusinessFaultFaultFaultMessage, ITTSServiceV1UpdatePersonSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.milleni.dunning.ws.client.tts.CreateTicklerResponseModel
     * @throws ITTSServiceV1CreateTicklerSystemFaultFaultFaultMessage
     * @throws ITTSServiceV1CreateTicklerBusinessFaultFaultFaultMessage
     */
    @WebMethod(operationName = "CreateTickler", action = "http://tempuri.org/ITTSServiceV1/CreateTickler")
    @WebResult(name = "CreateTicklerResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateTickler", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.tts.CreateTickler")
    @ResponseWrapper(localName = "CreateTicklerResponse", targetNamespace = "http://tempuri.org/", className = "org.milleni.dunning.ws.client.tts.CreateTicklerResponse")
    public CreateTicklerResponseModel createTickler(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        CreateTicklerRequestModel request)
        throws ITTSServiceV1CreateTicklerBusinessFaultFaultFaultMessage, ITTSServiceV1CreateTicklerSystemFaultFaultFaultMessage
    ;

}
