
package org.milleni.dunning.ws.client.tahsilat;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MilleniComOnlineTahsilat", targetNamespace = "http://milleni.com/online_tahsilat", wsdlLocation = "http://192.168.2.52/OnlineTahsilat/MilleniComOnlineTahsilat.asmx?wsdl")
public class MilleniComOnlineTahsilat
    extends Service
{

    private final static URL MILLENICOMONLINETAHSILAT_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.milleni.dunning.ws.client.tahsilat.MilleniComOnlineTahsilat.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.milleni.dunning.ws.client.tahsilat.MilleniComOnlineTahsilat.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.2.52/OnlineTahsilat/MilleniComOnlineTahsilat.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.2.52/OnlineTahsilat/MilleniComOnlineTahsilat.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MILLENICOMONLINETAHSILAT_WSDL_LOCATION = url;
    }

    public MilleniComOnlineTahsilat(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MilleniComOnlineTahsilat() {
        super(MILLENICOMONLINETAHSILAT_WSDL_LOCATION, new QName("http://milleni.com/online_tahsilat", "MilleniComOnlineTahsilat"));
    }

    /**
     * 
     * @return
     *     returns MilleniComOnlineTahsilatSoap
     */
    @WebEndpoint(name = "MilleniComOnlineTahsilatSoap")
    public MilleniComOnlineTahsilatSoap getMilleniComOnlineTahsilatSoap() {
        return super.getPort(new QName("http://milleni.com/online_tahsilat", "MilleniComOnlineTahsilatSoap"), MilleniComOnlineTahsilatSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MilleniComOnlineTahsilatSoap
     */
    @WebEndpoint(name = "MilleniComOnlineTahsilatSoap")
    public MilleniComOnlineTahsilatSoap getMilleniComOnlineTahsilatSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://milleni.com/online_tahsilat", "MilleniComOnlineTahsilatSoap"), MilleniComOnlineTahsilatSoap.class, features);
    }

}
